src/Employer.Web/Configuration/IoC.cs
src/Employer.Web/Controllers/NewVacancyController.cs
src/Employer.Web/Employer.Web.csproj
src/Employer.Web/Startup.ConfigureServices.cs
src/Recruit.Storage.Client/Core/Commands/CreateVacancyCommand.cs
src/Recruit.Storage.Client/Core/Handlers/CreateVacancyCommandHandler.cs
src/Recruit.Storage.Client/Core/Messaging/ICommand.cs
src/Recruit.Storage.Client/Core/Messaging/IMessaging.cs
src/Recruit.Storage.Client/Core/Messaging/MediatrMessaging.cs
src/Recruit.Storage.Client/Recruit.Storage.Client.csproj

- Added Mediatr
- An example command is submitted in NewVacancyController
- Moved IoC setup into own class
Can you check whether you are happy with the locations/names of the various files

ER-240 Mediatr, commands & messaging

---

src/Employer.Web/Configuration/ConfigurationExtensions.cs
src/Employer.Web/Configuration/IoC.cs
src/Employer.Web/Startup.ConfigureServices.cs

Also added a dependency resolver into ConfigureServices so can use IoC during configuration

Move Authorization out of ConfigureServices into an extension.

---

src/CosmosDb/Configuration.json

Added some test files to define a cosmosdb, collection and stored proc so that Ewan can test out the release process.

Add Cosmos Db config to test release process

---

src/Employer.Web/Startup.Configure.cs
src/Employer.Web/Views/Shared/_Layout.cshtml

- Fix CSP issue blocking font using data url
- Re-added AppInsights JS snippet
- Removed csp sources that are no longer relevant.

Fix csp issue

---

src/Employer.Web/Views/Dashboard/Index.cshtml
src/Employer.Web/Views/Home/Index.cshtml
src/Employer.Web/Views/Shared/_Layout.cshtml
src/Employer.Web/wwwroot/css/application.css

Added Floating menu styles (in progress)

Er 254 employer recruit ui

---

src/Employer.Web/appsettings.Development.json
src/Employer.Web/appsettings.json
src/Recruit.Vacancies.Client/Ioc/Registry.cs

Moved the connection string into ConnectionStrings configuration section.

Moved MongoDb ConnectionString

---

src/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json

Ewan, can you have a quick check that the way i've added the new connectionString is correct.
Are you happy for us to add new config values into the template going forward?

Update azure template with new config value for mongo

---

src/Employer.Web/appsettings.json
src/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json

@EwanNoble Added config to connect to the employer account api.

Account api config

---

src/Employer.Web/Views/Dashboard/Index.cshtml

Styled initial dashboard

---

src/Employer.Web/Configuration/IoC.cs
src/Employer.Web/Configuration/RouteNames.cs
src/Employer.Web/Controllers/DeleteVacancyController.cs
src/Employer.Web/Controllers/PreviewController.cs
src/Employer.Web/Orchestrators/DeleteVacancyOrchestrator.cs
src/Employer.Web/Orchestrators/SectionsOrchestrator.cs
src/Employer.Web/ViewModels/DeleteVacancy/DeleteEditModel.cs
src/Employer.Web/ViewModels/DeleteVacancy/DeleteViewModel.cs
src/Employer.Web/ViewModels/Sections/IndexViewModel.cs
src/Employer.Web/Views/DeleteVacancy/Delete.cshtml
src/Employer.Web/Views/Sections/Index.cshtml
src/Recruit.Vacancies.Client/Application/Commands/DeleteVacancyCommand.cs
src/Recruit.Vacancies.Client/Application/Handlers/DeleteVacancyCommandHandler.cs
src/Recruit.Vacancies.Client/Domain/Entities/Vacancy.cs
src/Recruit.Vacancies.Client/Infrastructure/Client/IVacancyClient.cs
src/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStore.cs
src/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Recruit.Vacancies.Client/Infrastructure/Repositories/StubVacancyRepository.cs

- Added handler to manage the deletion of draft vacancies
- Added new 'are you sure?' page which is displayed when clicking the 'delete' link

ER-250 Delete Draft Vacancy

---

src/Employer.Web/Startup.Configure.cs

Removed due to the asp validation summary tag adding inline styling

Remove CSP inline style check

---

src/Employer/Employer.Web/Configuration/IoC.cs
src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs
src/Employer/Employer.Web/Controllers/Part1/TrainingController.cs
src/Employer/Employer.Web/Controllers/Part1/WageController.cs
src/Employer/Employer.Web/Extensions/StringExtensions.cs
src/Employer/Employer.Web/Orchestrators/Part1/WageOrchestrator.cs
src/Employer/Employer.Web/ViewModels/Part1/Wage/WageEditModel.cs
src/Employer/Employer.Web/ViewModels/Part1/Wage/WageViewModel.cs
src/Employer/Employer.Web/ViewModels/ValidationMessages.cs
src/Employer/Employer.Web/ViewModels/Validations/TypeOfDateAttribute.cs
src/Employer/Employer.Web/ViewModels/Validations/TypeOfDecimalAttribute.cs
src/Employer/Employer.Web/ViewModels/Validations/TypeOfIntegerAttribute.cs
src/Employer/Employer.Web/ViewModels/Validations/TypeOfMoneyGBPAttribute.cs
src/Employer/Employer.Web/Views/Part1/Employer/Employer.cshtml
src/Employer/Employer.Web/Views/Part1/ShortDescription/ShortDescription.cshtml
src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml
src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml
src/Employer/UnitTests/Employer.Web/ViewModels/Part1/Training/TrainingEditModelTests.cs
src/Employer/UnitTests/Employer.Web/ViewModels/Part1/Wage/WageEditModelTests.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/Vacancy.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/Wage.cs
src/Shared/Recruit.Vacancies.Client/Domain/Enums/DurationUnit.cs
src/Shared/Recruit.Vacancies.Client/Domain/Enums/WageType.cs

- Ensuring dates must be yyyy
- Added Part1 section. Wages
- Updated validation messages as specified
- Using `<input type="number" />` 
- Ensuring custom validators only run if a value has been specified

ER-284 Wage section

---

src/Shared/Recruit.Vacancies.Client/Application/Handlers/UpdateDashboardCommandHandler.cs

- Nearly all of the functionality is already in place for this ticket
- Explicitly ordering by CreatedDate

ER-270 - Resuming a vacancy from the dashboard

---

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json

…g used by webjobs, specifically the EditVacancyInfo job

Update arm template to include setup for account api config for web jobs

---

src/Employer/Employer.Web/Employer.Web.csproj
src/Jobs/Recruit.Vacancies.Jobs/Recruit.Vacancies.Jobs.csproj

- Update NLog to RTM version.
- Update to NLog Redis target package with same change as above.

Update Logging packages

---

src/Jobs/Jobs.sln
src/Jobs/Recruit.Vacancies.Jobs/ApprenticeshipProgrammes/ApprenticeshipApiCollectionExtensions.cs
src/Jobs/Recruit.Vacancies.Jobs/Program.cs

Couple of small tidy up things in Jobs solution

Job tidy up

---

src/.vscode/launch.json
src/Employer/Employer.Web/Startup.Configure.cs
src/Employer/Employer.Web/appsettings.Development.json
src/Employer/Employer.Web/appsettings.json
src/Employer/Employer.Web/nlog.config
src/Jobs/Recruit.Vacancies.Jobs/Program.cs
src/Jobs/Recruit.Vacancies.Jobs/Recruit.Vacancies.Jobs.csproj
src/Jobs/Recruit.Vacancies.Jobs/appSettings.Development.json
src/Jobs/Recruit.Vacancies.Jobs/appSettings.json

- Added NLog filters to appSettings.json for Web and Jobs. Will allow us to tune the logging we want across the loggers.
- Tidy up the logging set up in WebJobs project and logging startup/shutdown of job.
- Logging web host startup and shutdown events.

Logging Update

---

src/Employer/Employer.Web/Controllers/DashboardController.cs
src/Employer/Employer.Web/ViewModels/DashboardViewModel.cs
src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Employer/Employer.Web/wwwroot/css/application.css

Styling dashboard warning message

Dashboardwarning

---

src/Employer/Employer.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml

Copy changes requested by PO

---

src/Employer/Employer.Web/Controllers/VacancyPreviewController.cs
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Employer/Employer.Web/wwwroot/css/application.css

Preview page changes to part 2 fields

Er 384 part2 banners

---

src/Employer/Employer.Web/Views/Part1/SearchResultPreview/SearchResultPreview.cshtml
src/Employer/Employer.Web/Views/Part2/AboutEmployer/AboutEmployer.cshtml
src/Employer/Employer.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml
src/Employer/Employer.Web/Views/Part2/Considerations/Considerations.cshtml
src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/Employer/Employer.Web/Views/Part2/Skills/Skills.cshtml
src/Employer/Employer.Web/Views/Part2/TrainingProvider/ConfirmTrainingProvider.cshtml
src/Employer/Employer.Web/Views/Part2/TrainingProvider/SelectTrainingProvider.cshtml
src/Employer/Employer.Web/Views/Part2/VacancyDescription/VacancyDescription.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml

Changes to add ids to buttons and links so that testers can write automated tests

Changes to add ids to buttons and links for selenium

---

src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml

Change to enable automation testing on Qualifications page

Change to help automated testing

---

src/QA/QA.Web/Configuration/StaffIdamsClaims.cs
src/QA/QA.Web/Controllers/ReviewController.cs
src/QA/QA.Web/Extensions/ClaimsPrincipalExtensions.cs
src/QA/QA.Web/Orchestrators/ReviewOrchestrator.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/StartVacancyReviewCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Application/Commands/StartVacancyReviewCommand.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/VacancyReview.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IQaVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/QaVacancyClient.cs

Update to ER-350 to log the user id of the staff idams user when the review is started.

ER-350 Log reviewer

---

src/Employer/Employer.Web/Views/Part1/SearchResultPreview/SearchResultPreview.cshtml
src/Employer/Employer.Web/Views/Shared/_NonEditableVacancyDisplayPartial.cshtml
src/Employer/Employer.Web/Views/Shared/_Part1Header.cshtml
src/Employer/Employer.Web/Views/Shared/_ValidationSummary.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Employer/Employer.Web/wwwroot/css/application.css
src/QA/QA.Web/Views/Review/Review.cshtml

Er 428 accessibility fixes

---

src/Shared/Recruit.Vacancies.Client/Application/Services/MinimumWage/StubNationalMinimumWageService.cs

https://www.gov.uk/national-minimum-wage-rates

Correcting national minimum wage lower bound

---

src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs
src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Shared/Recruit.Shared.Web/Extensions/EnumExtensions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateDashboardOnVacancyChange.cs

Employer shown different status to that of the underlying vacancy

Update status shown to the Employer

---

src/Data/CosmosDb/Configuration.json

- queryView & vacancyReviews effected.
- Will need to delete the collections from the environments before deployment.

ER-440 Add shard keys for collections

---

src/Jobs/Recruit.Vacancies.Jobs/appSettings.Development.json
src/Jobs/Recruit.Vacancies.Jobs/appSettings.json
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/GeocodeVacancyCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/Geocode/GeocodeServiceFactory.cs

Some changes flagged by Sachin during review.

ER-304 - Geocode review changes

---

src/Employer/Employer.Web/Configuration/ManageApprenticeshipsLinkHelper.cs
src/Employer/Employer.Web/Configuration/Routing/ManageApprenticeshipsRoutes.cs
src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs
src/Employer/Employer.Web/Controllers/ExternalLinksController.cs
src/Employer/Employer.Web/Views/Shared/_Layout.cshtml
src/Employer/Employer.Web/appsettings.Development.json
src/Employer/Employer.Web/appsettings.json

- 'Home' menu item now navigates to the current accounts landing page in MA.

Corrected links on Dashboard

---

src/Employer/Employer.Web/Controllers/Part1/EmployerController.cs
src/Employer/Employer.Web/Controllers/Part1/ShortDescriptionController.cs
src/Employer/Employer.Web/Controllers/Part1/TitleController.cs
src/Employer/Employer.Web/Orchestrators/Part1/ShortDescriptionOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/Part1/TitleOrchestrator.cs
src/Employer/Employer.Web/Utility.cs
src/Employer/Employer.Web/ViewModels/Part1/ShortDescription/ShortDescriptionEditModel.cs
src/Employer/Employer.Web/ViewModels/Part1/ShortDescription/ShortDescriptionViewModel.cs
src/Employer/Employer.Web/ViewModels/Part1/Title/TitleEditModel.cs
src/Employer/Employer.Web/ViewModels/Part1/Title/TitleViewModel.cs
src/Employer/Employer.Web/ViewModels/ValidationMessages.cs
src/Employer/Employer.Web/Views/Part1/Employer/Employer.cshtml
src/Employer/Employer.Web/Views/Part1/SearchResultPreview/SearchResultPreview.cshtml
src/Employer/Employer.Web/Views/Part1/ShortDescription/ShortDescription.cshtml
src/Employer/Employer.Web/Views/Part1/Title/Title.cshtml
src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml
src/Employer/Employer.Web/Views/Shared/_Part1Header.cshtml
src/Employer/UnitTests/Employer.Web/UtilityTests.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/CreateVacancyCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Application/Commands/CreateVacancyCommand.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs

Moved NumberOfPositions to Title screen
Change the ordering of Part 1 
from: Title > Employer > Short Description. 
to: Title > Short Description > Employer
Some minor front-end changes

ER-416 Part 1 ordering

---

src/Employer/Employer.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/QA/QA.Web/Mappings/ReviewMapper.cs

…ages in the employer web user journey and qa review screens where vacancy reference number is available.

ER-478 Display a 'VAC' prefixed vacancy reference number

---

src/Data/CosmosDb/Configuration.json
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs

- Add shard key into update for vacancy review.
- Increase RU limits.

Shard Key Changes

---

src/Employer/Employer.Web/Configuration/ConfigurationExtensions.cs
src/Employer/Employer.Web/Middleware/EmployerAccountHandler.cs
src/Employer/Employer.Web/Startup.Configure.cs
src/Employer/Employer.Web/Startup.ConfigureServices.cs

Removing use of Session and using a cookie to remember if we have rebuilt the employer's EditVanancyInfo

ER-337 - Removing Session

---

src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentExtensions.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/EmployerWebsiteUrlValidationTests.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/OfflineApplicationUrlValidationTests.cs

:boom: Have put comment in code ☹️ just to break down the rules for the url validation.

ER-508  - Strengthening the url validation

---

src/QA/QA.Web/Configuration/ServiceCollectionExtensions.cs

ER-481 - QA terminate session

---

src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentExtensions.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/EmployerWebsiteUrlValidationTests.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/OfflineApplicationUrlValidationTests.cs

Or any other input beginning or ending with a period character.

ER-508 - Updating validation for url to not allow .com

---

src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbCollectionBase.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/SequenceStore/MongoSequenceStore.cs

Log message contained non-existent context key with caused the retry logic to throw an Exception and bomb out.
We will release from this hotfix branch. Will also tag the HEAD of this branch with 1.0.3

Fix issue with Retry Policy

---

src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbCollectionBase.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/SequenceStore/MongoSequenceStore.cs

Reverts SkillsFundingAgency/das-recruit#156

Revert "Fix issue with Retry Policy"

---

src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbCollectionBase.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/SequenceStore/MongoSequenceStore.cs

Queries failing against mongo due to sorting across shards.
Moved the sorting into .Net code.

Hotfix shard issue

---

src/Employer/Employer.Web/Configuration/ConfigurationExtensions.cs
src/Employer/Employer.Web/Configuration/GoogleAnalyticsConfiguration.cs
src/Employer/Employer.Web/Configuration/IoC.cs
src/Employer/Employer.Web/Middleware/EmployerAccountHandler.cs
src/Employer/Employer.Web/Startup.Configure.cs
src/Employer/Employer.Web/Startup.ConfigureServices.cs
src/Employer/Employer.Web/Views/Shared/_GoogleAnalyticsPartial.cshtml
src/Employer/Employer.Web/Views/Shared/_Layout.cshtml
src/Employer/Employer.Web/appsettings.json
src/QA/QA.Web/Configuration/ServiceCollectionExtensions.cs
src/QA/QA.Web/Startup.Configure.cs
src/QA/QA.Web/Startup.ConfigureServices.cs

The Google Analytics code isn't sensitive and we should be able to track the live site with it. For testing we can just verify that the snippet is output on the page and we will get tracking data once we push to live.

er 483 er 500 er 576 various security issues addressesd and ga code

---

src/Employer/Employer.Web/wwwroot/css/application.css

Added additional style after issue found by Sultan

Er 511 delete button fix

---

src/Employer/Employer.Web/Configuration/CookieNames.cs
src/Employer/Employer.Web/Configuration/EsfaCookieOptions.cs
src/Employer/Employer.Web/Controllers/DashboardController.cs
src/Employer/Employer.Web/Middleware/EmployerAccountHandler.cs
src/Employer/Employer.Web/TagHelpers/EsfaDashboardBadgeTagHelper.cs
src/Employer/Employer.Web/ViewModels/DashboardViewModel.cs
src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Employer/Employer.Web/Views/Part1/Employer/Employer.cshtml
src/Employer/Employer.Web/Views/Part1/SearchResultPreview/SearchResultPreview.cshtml
src/Employer/Employer.Web/Views/Part1/ShortDescription/ShortDescription.cshtml
src/Employer/Employer.Web/Views/Part1/Title/Title.cshtml
src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml
src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml
src/Employer/Employer.Web/Views/Shared/_Layout.cshtml
src/Employer/Employer.Web/Views/Submitted/Confirmation.cshtml
src/Employer/Employer.Web/Views/VacancyManage/Approved.cshtml
src/Employer/Employer.Web/Views/VacancyManage/Closed.cshtml
src/Employer/Employer.Web/Views/VacancyManage/Live.cshtml
src/Employer/Employer.Web/Views/VacancyManage/Referred.cshtml
src/Employer/Employer.Web/Views/VacancyManage/Submitted.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/QA/QA.Web/Startup.ConfigureServices.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/AssignVacancyNumberCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/Dashboard/VacancySummary.cs

Have met the AC. Will need @sdholder to fix some styling alignment issues and markup cleanup 🙏 Lifted the markup from the prototype linked to from the JIRA ticket.

ER-320 employer dashboard filtering

---

src/Employer/Employer.Web/Views/ApplicationReview/ApplicationReview.cshtml
src/Employer/Employer.Web/Views/Part1/Employer/Employer.cshtml
src/Employer/Employer.Web/Views/Part1/ShortDescription/ShortDescription.cshtml
src/Employer/Employer.Web/Views/Part1/Title/Title.cshtml
src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml
src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml
src/Employer/Employer.Web/Views/Part2/AboutEmployer/AboutEmployer.cshtml
src/Employer/Employer.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml
src/Employer/Employer.Web/Views/Part2/Considerations/Considerations.cshtml
src/Employer/Employer.Web/Views/Part2/EmployerContactDetails/EmployerContactDetails.cshtml
src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/Employer/Employer.Web/Views/Part2/Skills/Skills.cshtml
src/Employer/Employer.Web/Views/Part2/VacancyDescription/VacancyDescription.cshtml
src/Employer/Employer.Web/wwwroot/javascripts/application.js

Functionality copied from other GDS sites

Added functionality to prevent multiple form submissions

---

src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs
src/Employer/Employer.Web/Controllers/ApplicationReviewController.cs
src/Employer/Employer.Web/Extensions/ApplicationReviewExtensions.cs
src/Employer/Employer.Web/Orchestrators/ApplicationReviewOrchestrator.cs
src/Employer/Employer.Web/ViewModels/ApplicationReview/ApplicationReviewEditModel.cs
src/Employer/Employer.Web/ViewModels/ApplicationReview/ApplicationReviewViewModel.cs
src/Employer/Employer.Web/ViewModels/ValidationMessages.cs
src/Employer/Employer.Web/Views/ApplicationReview/ApplicationReview.cshtml
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApplicationReviewCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Application/Commands/ApplicationReviewSuccessfulCommand.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/ApplicationReview.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/ApplicationReviewStatus.cs
src/Shared/Recruit.Vacancies.Client/Domain/Events/ApplicationReviewSuccessfulEvent.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IApplicationReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateDashboardOnVacancyChange.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateVacancyApplicationsOnApplicationReviewChange.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbApplicationReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/DashboardService.cs

- Added command `ApplicationReviewSuccessfulCommand`
- Added command handler `ApplicationReviewCommandHandler` to handle application review commands
- Added event `ApplicationReviewSuccessfulEvent`
After setting application review to 'Successful' an `ApplicationReviewSuccessfulEvent` is published.
This event is handled by:
- `UpdateDashboardOnVacancyChange` to rebuild the dashboard query view (there are new application counts against the vacancy that need updating)
- `UpdateVacancyApplicationsOnApplicationReviewChange` - to rebuild the applications against the vacancy
- In a future ticket we'll add an event handler to push a message to FAA to update it's application

ER-316 successful application

---

src/Employer/Employer.Web/Extensions/ApplicationReviewExtensions.cs
src/Employer/Employer.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Employer/Employer.Web/Orchestrators/Part1/SearchResultPreviewOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/Part1/TrainingOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs
src/Employer/Employer.Web/ViewModels/ApplicationReview/ApplicationReviewViewModel.cs
src/Employer/Employer.Web/ViewModels/VacancyManage/DisplayVacancyApplicationViewModel.cs
src/Employer/Employer.Web/ViewModels/VacancyManage/VacancyApplicationsViewModel.cs
src/Employer/Employer.Web/Views/ApplicationReview/ApplicationReview.cshtml
src/Employer/Employer.Web/Views/Part1/SearchResultPreview/SearchResultPreview.cshtml
src/Employer/Employer.Web/Views/Shared/_NonEditableVacancyDisplayPartial.cshtml
src/Employer/Employer.Web/Views/Shared/_VacancyApplicationsTablePartial.cshtml
src/Employer/Employer.Web/Views/Shared/_VacancySummaryDisplayPartial.cshtml
src/Employer/Employer.Web/Views/VacancyManage/ClosedWithApplications.cshtml
src/Employer/Employer.Web/Views/VacancyManage/LiveWithApplications.cshtml
src/QA/QA.Web/Mappings/ReviewMapper.cs
src/QA/QA.Web/Views/Review/Review.cshtml
src/Shared/Recruit.Vacancies.Client/Domain/Entities/ApplicationReviewDisabilityStatus.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/Vacancy.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateVacancyApplicationsOnApplicationReviewChange.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/VacancyApplications/VacancyApplication.cs

Showing an extra column with the disability status in the application reviews for Disability Confident applications.

ER-580 disability confidence application review

---

src/Employer/Employer.Web/Configuration/IoC.cs
src/Employer/Employer.Web/appsettings.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json
src/Employer/UnitTests/Employer.Web/ViewModels/ApplicationReview/ApplicationReviewEditModelTests.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApplicationReviewCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Domain/Events/ApplicationReviewedEvent.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateFAAOnApplicationReviewed.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/FaaApplicationStatus.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/FaaApplicationStatusSummary.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/FaaConfiguration.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/FaaService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/IFaaService.cs
src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs
src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/ApplicationReviewTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/EventHandlers/UpdateFAAOnApplicationReviewedTests.cs

DO NOT MERGE
- DevOps need to add the FAA service bus connection string before I'll merge this in (FaaConfiguration > StorageConnectionString) - ER-611
- Also FAA needs to be updated first so it can handle the v2 messages.
Added Microsoft.Azure.ServiceBus which is the .NET Standard client for Azure Service Bus.

ER-464 application notifications

---

setup/containers/docker-compose.yml

I've added the section but haven't tested it. :-(

Add azurite container

---

setup/Cosmos DB Emulator/Helpers.psm1
setup/Cosmos DB Emulator/Set-CosmosDbEmulator.ps1
setup/Cosmos DB Emulator/readme.md

A script that uses the `Configuration.json` to configure a local Azure Cosmos DB Emulator.
This will help:
- Testing of Configuration.json
- Updating development environment when the schema changes.

Script to configure local CosmosDB Emulator

---

src/Data/CosmosDb/Configuration.json
src/Data/Recruit.ChangeScripts/040-queryViews_MigrateDocuments_queryStore.js
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/IQueryStore.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStoreClient.cs

I have not been able to test my change script against a Cosmos sharded collection but have tested it against a collection in a local mongo container.

ER-593 changes for query store having view type shard key partition

---

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Console.RecruitSeedDataWriter.csproj
src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/BannedPhrases.json
src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/Profanities.json
src/Data/CosmosDb/Console.RecruitSeedDataWriter/SeedScript.ps1

…data into Cosmos referenceData collection.

ER-693 - Loading banned phrases and inoffensive profanities

---

src/Employer/Employer.Web/Orchestrators/Part2/SkillsOrchestrator.cs
src/Employer/UnitTests/Employer.Web/Orchestrators/Part2/SkillOrchestratorTests.cs
src/Shared/Recruit.Vacancies.Client/Application/Providers/ICandidateSkillsProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/Skills/CandidateSkillsProvider.cs
src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs

and refactored the orchestrator to use skill list instead of CandidateSkills

ER-681 Added CandidateSkillsProvider

---

src/Employer/Employer.Web/Employer.Web.csproj
src/Jobs/Recruit.Vacancies.Jobs/Recruit.Vacancies.Jobs.csproj
src/QA/QA.Web/QA.Web.csproj

Should make it easier for us to navigate/identify:
5a1b2a3e-7e99-42c8-a521-85e5ae34ae58 --> recruit-employer-web
0d60e5b4-1f4d-47b0-b24c-7bfa4d874849 --> recruit-webjob
e4d3aa1c-4b1e-4f85-a1c1-60c4fdf85b5f --> recruit-qa-web

Rename user secret ids

---

src/Employer/Employer.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs
src/Employer/Employer.Web/Views/Shared/_ReviewSummary.cshtml
src/Employer/Employer.Web/Views/Shared/_ValidationSummary.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Employer/Employer.Web/wwwroot/javascripts/application.js

Also changing preview page links to navigate correctly.

ER-666 - Changing summary anchor links class to summary

---

src/QA/QA.Web/appsettings.Development.json
src/Shared/Recruit.Shared.Web/RuleTemplates/BannedPhraseMessageTemplate.cs
src/Shared/Recruit.Shared.Web/RuleTemplates/RuleMessageTemplateRunner.cs
src/Shared/Recruit.Vacancies.Client/Application/Providers/IBannedPhrasesProvider.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/BaseRules/BaseBannedPhraseChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/BaseRules/BaseProfanityChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/BaseRules/ConsolidationOption.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/Engine/Rule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/Extensions/StringExtensions.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/RuleId.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyBannedPhraseChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyProfanityChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyRuleSet.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/BannedPhrasesData.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbConventions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/BannedPhrases/BannedPhraseList.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/BannedPhrases/BannedPhrasesProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/MongoDbReferenceDataRepository.cs
src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs
src/Shared/UnitTests/Vacancies.Client/Application/Rules/VacancyRules/VacancyProfanityChecksRuleTests.cs

Weighting and consolidation settings are hard coded for now.

ER-701 banned phrases rule

---

src/Shared/Recruit.Shared.Web/Recruit.Shared.Web.csproj
src/Shared/Recruit.Shared.Web/RuleTemplates/IRuleMessageTemplateRunner.cs
src/Shared/Recruit.Shared.Web/RuleTemplates/RuleMessageTemplateRunner.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/BaseRules/BaseBannedPhraseChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/BaseRules/BaseProfanityChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/Engine/Rule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyTitlePopularityCheckRule.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/RuleOutcome.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Configuration/ConfigurationReader.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbCollectionNames.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbConventions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbNames.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/MongoDbReferenceDataRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbApplicationReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/SequenceStore/MongoSequenceStore.cs
src/Shared/UnitTests/Vacancies.Client/Application/Rules/VacancyRules/VacancyTitlePopularityCheckRuleTests.cs

If there is a json parse error when deserializing we probably want it to bubble up.

ER-723 change rule outcome data field type to string

---

src/QA/QA.Web/Configuration/HostSettings.cs
src/QA/QA.Web/Program.cs
src/QA/QA.Web/Startup.Configure.cs

Reverted Https redirection changes as is causing warnings to be output in the logs.

Revert redirect changes in QA App

---

src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs
src/Employer/Employer.Web/Controllers/EditVacancyDatesController.cs
src/Employer/Employer.Web/Controllers/VacancyManageController.cs
src/Employer/Employer.Web/Controllers/VacancyViewController.cs
src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/VacancyViewOrchestrator.cs
src/Employer/Employer.Web/ViewModels/VacancyManage/EditVacancyViewModel.cs
src/Employer/Employer.Web/ViewModels/VacancyManage/ManageVacancyViewModel.cs
src/Employer/Employer.Web/ViewModels/VacancyView/VacancyApplicationsViewModel.cs
src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Employer/Employer.Web/Views/PartialNames.cs
src/Employer/Employer.Web/Views/Shared/_EditVacancyPartial.cshtml
src/Employer/Employer.Web/Views/Shared/_VacancyApplicationsTablePartial.cshtml
src/Employer/Employer.Web/Views/VacancyManage/EditVacancy.cshtml
src/Employer/Employer.Web/Views/VacancyManage/ManageVacancy.cshtml
src/Employer/Employer.Web/Views/VacancyView/ClosedWithApplications.cshtml
src/Employer/Employer.Web/Views/VacancyView/LiveWithApplications.cshtml
src/Employer/Employer.Web/wwwroot/css/application.css
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/Employer/VacancySummary.cs

The Clone and Close vacancy links are stubbed for the moment.
Have created a ManageVacancyViewModel for the page that doesn't inherit from the DisplayVacancyViewModel class as for the moment the ManageVacancyViewModel doesn't need as many properties.

ER-712 - Manage vacancy view

---

src/Shared/UnitTests/UnitTests.csproj
src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/CloneVacancyCommandHandlerTests.cs

- Added test as suggested in code review that was missed.

ER-452 Add test for clone command handler

---

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json

If we can get this ARM template in, it would be okay as the next PR will have the code that uses it within the project/job.

ER-797 - ARM template updates for non levy employer job

---

src/Employer/Employer.Web/ViewModels/ValidationMessages.cs
src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/WageValidationTests.cs

These were reviewed with Karen

ER-804 validation messages review pass1

---

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json

Move WebJobs App service off ASE and to own App service plan
WebJob App Service Plan uses das-platform-building-blocks template.
VSTS config will be edited before merging.

Dasd 3798/feature move web jobs app service off ase and to own app service plan

---

src/Employer/Employer.Web/Controllers/ErrorController.cs
src/Employer/Employer.Web/Controllers/LogoutController.cs
src/Employer/Employer.Web/Extensions/HttpContextExtensions.cs

**Waiting for DevOps to restart the employerusers cloud services to allow testing**
On signout from recruit it will now redirect to the idams "You've logged out" page. This page contains iframes with the src for the signout of all the other subsites.
- Removed Redirect in logout as was blocking the required behaviour of oidc middleware
- Removed Logout from Blocked User story as this isn't required.

ER-718 Implement SSO

---

src/Data/CosmosDb/Configuration.json

Remove the vacancyReviews collection from cosmos config

Remove old collection from config

---

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/MinimumWageRanges.json
src/Employer/Employer.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Employer/Employer.Web/Orchestrators/Part1/SearchResultPreviewOrchestrator.cs
src/QA/QA.Web/Mappings/ReviewMapper.cs
src/Shared/Recruit.Shared.Web/Extensions/WageExtensions.cs
src/Shared/Recruit.Vacancies.Client/Application/Providers/IMinimumWageProvider.cs
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/CustomValidators/VacancyValidators/VacancyFluentValidationExtensions.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/IMinimumWage.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/WageRange.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/Wages/MinimumWage.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/Wages/NationalMinimumWageProvider.cs
src/Shared/UnitTests/Shared.Web/Extensions/WageExtensionsTests.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/CrossField/FixedWageAmountValidation.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Providers/NationalMinimumWageProviderTests.cs

- Added 2019 wages
- Removed ValidTo from Minimum wage.  (Uses the start of the next period to determine end)
- Added the period year to the validation message

ER-814 minimum wages 2019

---

src/Employer/Employer.Web/Controllers/ErrorController.cs

ER-812 - Explicitly setting status to 500

---

src/Employer/Employer.Web/Controllers/CreateVacancyOptionsController.cs
src/Employer/Employer.Web/Mappings/DashboardMapper.cs
src/Employer/Employer.Web/ViewModels/CreateVacancyOptions/CreateVacancyOptionsViewModel.cs
src/Employer/Employer.Web/ViewModels/DashboardViewModel.cs
src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Employer/Employer.Web/Views/Submitted/Confirmation.cshtml

Created a new 'create' endpoint that redirects to either the list of cloned vacancies or starts a new vacancy.

ER-796 - Create vacancy from Dashboard and Submitted pages

---

src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs
src/Employer/Employer.Web/Controllers/CookieManagerController.cs
src/Employer/Employer.Web/Startup.Configure.cs
src/Employer/Employer.Web/Views/Shared/_Layout.cshtml
src/Employer/Employer.Web/Views/Shared/_LayoutWithoutNavigation.cshtml
src/Employer/Employer.Web/wwwroot/css/application.css

This is an enhancement to the item I did previously. Performing an open redirect based on the incoming `Referer` is bad practice as the referer could be an external site.
Happy to make changes if someone has a more appropriate solution.

ER-651 - Moving away from open redirect 

---

src/Employer/Employer.Web/appsettings.Development.json
src/Employer/Employer.Web/appsettings.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/QA/QA.Web/appsettings.Development.json
src/QA/QA.Web/appsettings.json

- Missed updating the config for the Employer and Qa site before

Rename storage queue connection string

---

GitVersion.yml

to track version bump instruction in commit merge messages and hopefully rebase squashes

Adding GitVersion.yml file 

---

src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs
src/Shared/Recruit.Vacancies.Client/Domain/Extensions/DateTimeExtensions.cs

ER-783 - Changing application closing date validation message

---

src/Employer/Employer.Web/Views/Part1/ShortDescription/ShortDescription.cshtml
src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/Employer/Employer.Web/Views/Part2/Skills/Skills.cshtml
src/Employer/Employer.Web/wwwroot/css/application.css

ER-773 - Skills and Qualifications content change
ER-762 - Short Description content change

ER-773 & ER-762 content

---

src/Employer/Employer.Web/Mappings/Extensions/IApprenticeshipProgrammeMapperExtensions.cs
src/Employer/Employer.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Employer/Employer.Web/appsettings.json

ER-764 - Training programmes dropdown content change
ER-761 - Vacancy preview link to FAA content

ER-761 & ER-764 content tweaks

---

src/Shared/Recruit.Vacancies.Client/Application/EventHandlers/NotifyOnVacancyActions.cs
src/Shared/Recruit.Vacancies.Client/Application/Services/INotifyVacancyReviewUpdates.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Slack/SlackNotifyVacancyReviewUpdates.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Slack/SlackNotifyVacancyReviewUpdatesTests.cs

so we can easily see resubmissions, etc.

added more info to the QA review slack messages

---

src/Data/Recruit.ChangeScripts/2018-12-17_010-qualification-equivalent.js

Removed the batching as it would only update the same 500 documents on each pass-through

ER-821 - Fixing update script as only updated first 500 documents

---

src/Employer/Employer.Web/Views/Part1/Employer/Employer.cshtml
src/Employer/Employer.Web/Views/Part1/ShortDescription/ShortDescription.cshtml
src/Employer/Employer.Web/Views/Part1/Title/Title.cshtml
src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml
src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml

I had to use IsWizard to show the back link as HasCompletedPartOne was set to true on the preview page, but user is allowed to get back in to the wizard from there.

ER-854 part1 back link

---

src/Employer/Employer.Web/Orchestrators/Part2/VacancyDescriptionOrchestrator.cs
src/Shared/Recruit.Vacancies.Client/Application/Services/HtmlSanitizerService.cs
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/CustomValidators/HtmlValidator.cs
src/Shared/UnitTests/Vacancies.Client/Application/Services/HtmlSanitizerServiceTests.cs

- Only running the sanitizer as part of validation and not on post.
- If the sanitization process only returns HTML whitespace then fail validation

ER-858 - Html validation improvements

---

src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs

Added timing info for published vacancy recreation job

ER-850 - Added logging to published vacancy recreation job

---

src/Employer/Employer.Web/wwwroot/javascripts/application.js
src/Provider/Provider.Web/wwwroot/javascripts/application.js
src/QA/QA.Web/wwwroot/javascripts/application.js

Stripping styling when pasting into a HTML editor

ER-858 - Added TinyMCE paste plugin to paste as text

---

src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/Employer/Employer.Web/Views/Part2/Skills/Skills.cshtml
src/Employer/Employer.Web/Views/Part2/TrainingProvider/SelectTrainingProvider.cshtml

Fixed and added some missing validation messages in Employer

ER-706 - Validation message fixes

---

src/QA/QA.Web/ViewModels/VacancyReviewSearchResultViewModel.cs
src/QA/QA.Web/Views/Dashboard/Index.cshtml

These flags on review model are so confusing... I have applied a patch here... going to add a tech debt to fix these flags properly.

ER-669 Closed reviews shouldn't have assignment note

---

src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs
src/Provider/Provider.Web/Controllers/Part2/VacancyDescriptionController.cs
src/Provider/Provider.Web/Orchestrators/Part2/VacancyDescriptionOrchestrator.cs
src/Provider/Provider.Web/Startup.ConfigureServices.cs
src/Provider/Provider.Web/ViewModels/Part2/VacancyDescription/VacancyDescriptionEditModel.cs
src/Provider/Provider.Web/ViewModels/Part2/VacancyDescription/VacancyDescriptionViewModel.cs
src/Provider/Provider.Web/Views/Part2/VacancyDescription/VacancyDescription.cshtml
src/Provider/Provider.Web/Views/PartialNames.cs
src/Provider/Provider.Web/Views/Shared/_Layout.cshtml

First of the Part 2 screens.
Copy and paste from Employer.
The view I've copied from Steve's GDS branch.
What do we want to do about PRs? Shall we merge into ER-922 for now?

ER-879 - Part 2 Long Descriptions

---

src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Controllers/Part1/ShortDescriptionController.cs
src/Provider/Provider.Web/Controllers/Part1/TitleController.cs
src/Provider/Provider.Web/Orchestrators/Part1/ShortDescriptionOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part1/ShortDescription/ShortDescriptionEditModel.cs
src/Provider/Provider.Web/ViewModels/Part1/ShortDescription/ShortDescriptionViewModel.cs
src/Provider/Provider.Web/Views/Part1/ShortDescription/ShortDescription.cshtml
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/IQueryStoreWriter.cs

This is exact copy of the Employer, no changes.

ER-874 Implements short description

---

src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Controllers/Part2/ApplicationProcessController.cs
src/Provider/Provider.Web/Orchestrators/Part2/ApplicationProcessOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part2/ApplicationProcess/ApplicationProcessEditModel.cs
src/Provider/Provider.Web/ViewModels/Part2/ApplicationProcess/ApplicationProcessViewModel.cs
src/Provider/Provider.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml
src/Provider/Provider.Web/wwwroot/javascripts/application.js

The controller & orchestrator are equivalent to Employer so have all the functionality to create offline/online vacancies.
For private beta we are only doing offline vacancies so the only code change I've needed to do is make a temporary modification to the View.

ER-885 - Part 2 Application Process

---

src/.vscode/launch.json
src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Controllers/Part1/LocationController.cs
src/Provider/Provider.Web/Controllers/Part1/ShortDescriptionController.cs
src/Provider/Provider.Web/Controllers/Part1/TrainingController.cs
src/Provider/Provider.Web/Orchestrators/Part1/LocationOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/Part1/ShortDescriptionOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/Part1/TrainingOrchestrator.cs
src/Provider/Provider.Web/Utility.cs
src/Provider/Provider.Web/ViewModels/Part1/Training/ApprenticeshipProgrammeViewModel.cs
src/Provider/Provider.Web/ViewModels/Part1/Training/TrainingEditModel.cs
src/Provider/Provider.Web/ViewModels/Part1/Training/TrainingViewModel.cs
src/Provider/Provider.Web/Views/Part1/Training/Training.cshtml
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs

This is exact copy of employers

ER-876 Implements important dates and training step in part1

---

src/.vscode/launch.json
src/Employer/Employer.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs
src/Provider/Provider.Web/Controllers/Part1/SearchResultPreviewController.cs
src/Provider/Provider.Web/Controllers/Part1/WageController.cs
src/Provider/Provider.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Provider/Provider.Web/Orchestrators/Part1/SearchResultPreviewOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part1/SearchResultPreview/SearchResultPreviewViewModel.cs
src/Provider/Provider.Web/Views/Part1/SearchResultPreview/SearchResultPreview.cshtml
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IRecruitVacancyClient.cs

This is exact copy of the employers.

ER-878 Implements provider part1 preview page

---

src/QA/QA.Web/Mappings/ReviewMapper.cs
src/QA/QA.Web/ViewModels/ReviewViewModel.cs
src/QA/QA.Web/Views/Review/ReadonlyReview.cshtml
src/QA/QA.Web/Views/Review/Review.cshtml

This follows on from ER-935 so contains commits from this PR.

ER-887 - QA Provider review

---

src/QA/QA.Web/Views/Shared/_Layout.cshtml
src/QA/QA.Web/Views/Shared/_ReviewHeader.cshtml
src/QA/QA.Web/wwwroot/css/application.css

Er 868 provider user stats

---

src/Employer/Employer.Web/Views/CloseVacancy/Close.cshtml
src/Employer/Employer.Web/Views/EditVacancyDates/EditVacancyDates.cshtml
src/Employer/Employer.Web/Views/Part1/SearchResultPreview/SearchResultPreview.cshtml
src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml
src/Employer/Employer.Web/Views/Part2/AboutEmployer/AboutEmployer.cshtml
src/Employer/Employer.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml
src/Employer/Employer.Web/Views/Part2/EmployerContactDetails/EmployerContactDetails.cshtml
src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/QA/QA.Web/wwwroot/css/application.css

Style changes as result of journey walk through with UX

Gds ux style review

---

src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Employer/Employer.Web/Views/VacancyManage/ManageVacancy.cshtml
src/Provider/Provider.Web/Views/Dashboard/Dashboard.cshtml

Most of the code already existed. Making minor code changes.

Making Text Manage visible on the dashboard for provider.

---

src/Employer/Employer.Web/Views/VacancyManage/ManageVacancy.cshtml
src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/ViewNames.cs
src/Provider/Provider.Web/Controllers/CloseVacancyController.cs
src/Provider/Provider.Web/Model/VacancyInfo.cs
src/Provider/Provider.Web/Orchestrators/CloseVacancyOrchestrator.cs
src/Provider/Provider.Web/ViewModels/CloseVacancy/CloseEditModel.cs
src/Provider/Provider.Web/ViewModels/CloseVacancy/CloseViewModel.cs
src/Provider/Provider.Web/Views/CloseVacancy/Close.cshtml
src/Provider/Provider.Web/Views/VacancyManage/ManageVacancy.cshtml
src/Provider/UnitTests/Provider.Web/Orchestrators/Part2/SkillOrchestratorTests.cs
src/Provider/UnitTests/Provider.Web/UtilityTests/CheckRouteIsValidForVacancyTests.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs

Mainly copy paste from Employer!

ER-870 close vacancy

---

src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Controllers/DashboardController.cs
src/Provider/Provider.Web/Controllers/EditVacancyDatesController.cs
src/Provider/Provider.Web/Orchestrators/EditVacancyDatesOrchestrator.cs
src/Provider/Provider.Web/ViewModels/EditVacancyDates/EditVacancyDatesEditModel.cs
src/Provider/Provider.Web/ViewModels/EditVacancyDates/EditVacancyDatesViewModel.cs
src/Provider/Provider.Web/Views/EditVacancyDates/EditVacancyDates.cshtml
src/Provider/Provider.Web/Views/VacancyManage/ManageVacancy.cshtml
src/Provider/Provider.Web/Views/VacancyView/ClosedWithApplications.cshtml
src/Provider/Provider.Web/Views/VacancyView/LiveWithApplications.cshtml
src/Shared/Recruit.Shared.Web/Orchestrators/EntityValidatingOrchestrator.cs

Most of it is a copy from Employer.
I have commented out the bits that refer to live applications. I will handle them as part of ER-974

Er 994 extend vacancies

---

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json
src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/SetupProviderHandler.cs
src/Jobs/Recruit.Vacancies.Jobs/ServiceCollectionExtensions.cs
src/Jobs/Recruit.Vacancies.Jobs/appSettings.Development.json
src/Jobs/Recruit.Vacancies.Jobs/appSettings.json
src/Provider/Provider.Web/Orchestrators/Part1/EmployerOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/Part1/TitleOrchestrator.cs
src/Shared/Recruit.Vacancies.Client/Application/EventHandlers/RePublishEventToEventStoreEventHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/EditVacancyInfo/EmployerInfo.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStoreClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/EmployerAccount/EmployerAccountProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/EmployerAccount/IEmployerAccountProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/Projections/EditVacancyInfoProjectionService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/Projections/IEditVacancyInfoProjectionService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/IProviderRelationshipsService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/LegalEntityDto.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/ProviderPermissions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/ProviderRelationshipApiConfiguration.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/ProviderRelationshipsService.cs
src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs
src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj

I have create ProviderRelationshipsService which queries provider relationships api. I wasn't able to use the api client, hence the DTOs required are embedded within this service class as they shouldn't surface anywhere else. Also I have added config required for provider relationships api.

ER-925 Update provider vacancy edit info job

---

src/Employer/Employer.Web/Configuration/IoC.cs
src/Jobs/Recruit.Vacancies.Jobs/ServiceCollectionExtensions.cs
src/Provider/Provider.Web/Configuration/IoC.cs
src/QA/QA.Web/Startup.ConfigureServices.cs
src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs

We're retrieving the QaRules from the DB on every page request for Employer and Provider. So suggesting we change to Singleton.

Changed QaRulesConfiguration to Singleton

---

src/Shared/Recruit.Vacancies.Client/Application/Providers/IBankHolidayProvider.cs
src/Shared/Recruit.Vacancies.Client/Application/Services/SlaService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/ApprenticeshipProgrammes/ApprenticeshipApiCollectionExtensions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/ApprenticeshipProgrammes/ApprenticeshipProgrammeProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/ApprenticeshipProgrammes/ApprenticeshipProgrammesUpdateService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/BankHolidays/BankHolidayProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/BankHolidays/BankHolidayUpdateService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/BankHolidays/BankHolidays.cs
src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj
src/Shared/UnitTests/Vacancies.Client/Infrastructure/ReferenceData/ApprenticeshipProgrammes/ApprenticeshipProgrammesUpdaterServiceTests.cs

Validation mainly is mainly on Bankholidays, Standards and Frameworks.

Er-965_Validate reference data

---

src/Employer/Employer.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs
src/Provider/Provider.Web/Configuration/Routing/RoutePaths.cs
src/Provider/Provider.Web/Controllers/Reports/ProviderApplicationsReportController.cs
src/Provider/Provider.Web/Controllers/Reports/ReportDashboardController.cs
src/Provider/Provider.Web/Orchestrators/Reports/ProviderApplicationsReportOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/Reports/ReportDashboardOrchestrator.cs
src/Provider/Provider.Web/Startup.ConfigureServices.cs
src/Provider/Provider.Web/ViewModels/Reports/DateRangeType.cs
src/Provider/Provider.Web/ViewModels/Reports/ProviderApplicationsReport/ProviderApplicationsReportCreateEditModel.cs
src/Provider/Provider.Web/ViewModels/Reports/ProviderApplicationsReport/ProviderApplicationsReportCreateEditModelValidator.cs
src/Provider/Provider.Web/ViewModels/Reports/ProviderApplicationsReport/ProviderApplicationsReportCreateViewModel.cs
src/Provider/Provider.Web/ViewModels/Reports/ReportDashboard/ReportsDashboardViewModel.cs
src/Provider/Provider.Web/Views/Reports/ProviderApplicationsReport/Create.cshtml
src/Provider/Provider.Web/Views/Reports/ReportDashboard/Dashboard.cshtml
src/Provider/UnitTests/Provider.Web/ViewModels/Reports/ProviderApplicationsReport/ProviderApplicationsReportCreateEditModelValidatorTests.cs

The reporting story is going to be quite big so I'm going to batch it into a series of PRs which I'll merge into the `ER-470_reporting_main` branch.
Once this is feature complete I'll merge `ER-470_reporting_main` into `main`.
This PR is for:
- The Reporting Dashboard controller/orch/view (not fully featured yet)
- The Provider Applications Report controller/orch/view/validations

ER-470 - Provider Reporting. Web & parameter validation

---

src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/VacancySummariesProvider/VacancySummariesProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/VacancySummariesProvider/VacancySummaryAggQueryBuilder.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/VacancySummariesProvider/VacancySummaryAggQueryResponseDto.cs

Not happy about this but this is just a temp fix which should allow the dashboard to generate properly and unblock QA.
Will be looking into re-instating the grouping as part of the Aggregate Pipeline very soon.

Temp fix around application review counts on employer dashboard

---

src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Provider/Provider.Web/Views/Dashboard/Dashboard.cshtml
src/Shared/Recruit.Shared.Web/ViewModels/VacancySummaryViewModel.cs

This is something I missed out of the provider allow create applications vacancy story. Got kicked back from PO acceptance. An addition has been made to Employer as well.

Add applications columns to dashboards

---

src/Employer/Employer.Web/Orchestrators/EditVacancyDatesOrchestrator.cs
src/Employer/Employer.Web/Views/EditVacancyDates/EditVacancyDates.cshtml
src/Employer/Employer.Web/Views/Shared/_EditVacancyPartial.cshtml
src/Employer/Employer.Web/Views/VacancyManage/EditVacancy.cshtml
src/Provider/Provider.Web/Views/EditVacancyDates/EditVacancyDates.cshtml
src/Provider/Provider.Web/Views/Shared/_EditVacancyPartial.cshtml
src/Provider/Provider.Web/Views/VacancyManage/ManageVacancy.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/ErrorMessages.cs
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Extensions/VacancyExtensions.cs

Making changes to match the template.

Ui fixes manage applications

---

src/QA/QA.Web/Views/Shared/_ReviewHeader.cshtml
src/QA/QA.Web/wwwroot/css/application.css

Minor text and style changes on the _reviewHeader page.

ER-1022_Text change as per template.

---

src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs
src/Employer/Employer.Web/Controllers/DeleteVacancyController.cs
src/Employer/Employer.Web/Views/DeleteVacancy/Delete.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs
src/Provider/Provider.Web/Controllers/DeleteVacancyController.cs
src/Provider/Provider.Web/Orchestrators/DeleteVacancyOrchestrator.cs
src/Provider/Provider.Web/ViewModels/DeleteVacancy/DeleteEditModel.cs
src/Provider/Provider.Web/ViewModels/DeleteVacancy/DeleteViewModel.cs
src/Provider/Provider.Web/Views/DeleteVacancy/Delete.cshtml
src/Provider/Provider.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/ProviderVacancyClient.cs

ER-892:Delete Vacancy functionality for provider.

---

src/Shared/Recruit.Vacancies.Client/Domain/Entities/Vacancy.cs

ER-1083:Ability to delete rejected vacancies.

---

src/Jobs/Recruit.Vacancies.Jobs/Reports/DeleteReportsJob.cs
src/Shared/Recruit.Vacancies.Client/Application/Providers/ITimeProvider.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IReportRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbReportRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/CurrentUtcTimeProvider.cs

This is the last PR for this ticket! 
This is a nightly job that deletes reports that are over 7 days old.

ER-470 Reporting delete job

---

src/Provider/Provider.Web/Orchestrators/Reports/ReportDashboardOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Reports/ProviderApplicationsReport/ProviderApplicationsReportCreateViewModel.cs
src/Provider/Provider.Web/ViewModels/Reports/ReportDashboard/ReportsDashboardViewModel.cs
src/Provider/Provider.Web/Views/Reports/ProviderApplicationsReport/Create.cshtml
src/Provider/Provider.Web/Views/Reports/ReportDashboard/Dashboard.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Services/Reports/IReportService.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IReportRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/ProviderVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Reports/ReportService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbReportRepository.cs

OK so I said the last PR was the final PR for reporting however it appears not.
- Incrementing the download count every time a report is downloaded
- Minor tweaks to align with the story

ER-470 - Updating DownloadCount on download and minor tweaks.

---

src/QA/QA.Web/Orchestrators/DashboardOrchestrator.cs
src/QA/QA.Web/ViewModels/VacancyReviewSearchResultViewModel.cs
src/QA/QA.Web/Views/Dashboard/Index.cshtml

Show deleted message on QA dashboard. Not building.

---

src/Provider/Provider.Web/Orchestrators/Reports/ProviderApplicationsReportOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/Reports/ReportDashboardOrchestrator.cs
src/Provider/UnitTests/Provider.Web/Orchestrators/Reports/ProviderApplicationsReportOrchestratorTests.cs
src/Shared/Recruit.Shared.Web/Extensions/StringExtensions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Reports/CsvBuilder.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Reports/ReportService.cs

Some fixes for issue raised during QA.
- Ensuring reporting parameters are UTC but displayed using local time
- Making the report header look more like v1 reports.

ER-470 reporting fixes

---

src/Employer/Employer.Web/Views/Error/AccessDenied.cshtml
src/Provider/Provider.Web/Middleware/ProviderAccountHandler.cs
src/QA/QA.Web/Views/Error/AccessDenied.cshtml

Funny what you wake up thinking about....
I'd removed this `else` in the previous PR which added the Provider service claim authorisation.  
If UKPRN isn't specified in the route then we should allow.

ER-1192 - Provider service claim.

---

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Provider/Provider.Web/Filters/CheckProviderBlockedFilter.cs
src/Provider/Provider.Web/Views/Error/ProviderBlocked.cshtml
src/Provider/Provider.Web/appsettings.Development.json
src/Provider/Provider.Web/appsettings.json
src/Shared/Recruit.Shared.Web/Configuration/EnvironmentNames.cs

This will be merged to master and then tested  on PreProd.

ER-866_Testing on Preprod.

---

src/Employer/Employer.Web/Controllers/LegalEntityAgreementController.cs
src/Employer/Employer.Web/Controllers/Part1/EmployerController.cs
src/Employer/Employer.Web/Controllers/Part1/EmployerNameController.cs
src/Employer/Employer.Web/Views/Part1/Employer/Employer.cshtml
src/Employer/Employer.Web/Views/Part1/EmployerName/EmployerName.cshtml
src/Employer/Employer.Web/Views/Part1/Location/Location.cshtml
src/Provider/Provider.Web/Controllers/Part1/EmployerNameController.cs
src/Provider/Provider.Web/Controllers/Part1/LegalEntityController.cs
src/Provider/Provider.Web/Views/Part1/EmployerName/EmployerName.cshtml
src/Provider/Provider.Web/Views/Part1/LegalEntity/LegalEntity.cshtml
src/Provider/Provider.Web/Views/Part1/Location/Location.cshtml

This perhaps fixes all the sub journey navigation issues. Needs testing before it can be merged, as I haven't tested all the scenarios due to short of time.

ER-1093 This fixes all the navigation issues

---

src/Employer/Employer.Web/Views/Error/AccessDenied.cshtml
src/Provider/Provider.Web/Configuration/ViewNames.cs
src/Provider/Provider.Web/Controllers/CloneVacancyController.cs
src/Provider/Provider.Web/Controllers/ErrorController.cs
src/Provider/Provider.Web/Exceptions/MissingPermissionsException.cs
src/Provider/Provider.Web/Exceptions/RecruitWebExceptionMessages.cs
src/Provider/Provider.Web/Filters/CheckProviderBlockedFilter.cs
src/Provider/Provider.Web/Orchestrators/CloneVacancyOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/Part1/EmployerOrchestrator.cs
src/Provider/Provider.Web/ViewModels/MissingPermissionsViewModel.cs
src/Provider/Provider.Web/Views/Error/AccessDenied.cshtml
src/Provider/Provider.Web/Views/Error/MissingPermissions.cshtml
src/Provider/UnitTests/Provider.Web/Orchestrators/CloneVacancyOrchestratorTest/CloneVacancyOrchestratorTestBase.cs
src/Provider/UnitTests/Provider.Web/Orchestrators/CloneVacancyOrchestratorTest/GetCloneableAuthorisedVacancyAsyncTests.cs
src/QA/QA.Web/Views/Error/AccessDenied.cshtml
src/Shared/Recruit.Shared.Web/Models/RecruitVacancyAction.cs
src/Shared/Recruit.Shared.Web/Models/VacancyActionType.cs

… vacancy on Provider recruit and not having required legal entity level permission +semver: patch

ER-1081 - Show missing permission content page when creating/cloning

---

src/Employer/Employer.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Employer/Employer.Web/Views/Part1/EmployerName/EmployerName.cshtml
src/QA/QA.Web/Mappings/ReviewMapper.cs
src/QA/QA.Web/ViewModels/ReviewViewModel.cs
src/QA/QA.Web/Views/Review/Review.cshtml
src/Shared/Recruit.Shared.Web/Extensions/VacancyExtensions.cs
src/Shared/Recruit.Shared.Web/Mappers/FieldDisplayNameResolver.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyBannedPhraseChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyProfanityChecksRule.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IVacancyReviewQuery.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IQaVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/QaVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateLiveVacancyOnVacancyChange.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/VacancyClosedEventHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Extensions/VacancyExtensions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/Vacancy/VacancyProjectionBase.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/Projections/PublishedVacancyProjectionService.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Extensions/VacancyExtensionsTests.cs

- Running profanity and banned phrase check on Anonymous employer description
- When creating the vacancy projection I am removing the EmployerWebsite and only returning the Outcode for the address.

ER-1019 QA Anonymous employers

---

src/Provider/Provider.Web/Extensions/ClaimsPrincipalExtensions.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/UserSignedInCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/User.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/VacancyUser.cs

For Provider users we are now storing their email address and UKPRN.
Email and UKPRN get patched on every provider user log in.

ER-1226 - Provider user. Storing email and Ukprn

---

setup/containers/.docker/logstash.dockerfile
setup/containers/docker-compose.yml

Will need to rebuild the logstash image to update using `docker-compose build` prior to running the container set

Updating local ELK to v7

---

src/Provider/Provider.Web/Orchestrators/DashboardOrchestrator.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/VacancySummary.cs

To fix bugs raised in ER-1151.

ER-1151-Update DashboardOrchestrator.cs

---

src/QA/QA.Web/Views/Review/Review.cshtml
src/Shared/Recruit.Shared.Web/RuleTemplates/RuleMessageTemplateRunner.cs
src/Shared/Recruit.Shared.Web/RuleTemplates/VacancyAnonymousMessageTemplate.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/RuleId.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyAnonymousCheckRule.cs
src/Shared/Recruit.Vacancies.Client/Application/Rules/VacancyRules/VacancyRuleSet.cs
src/Shared/UnitTests/Vacancies.Client/Application/Rules/VacancyRules/VacancyAnonymousCheckRuleTests.cs

A new auto QA rule that checks if the vacancy is Anonymous

ER-1019 - Added VacancyAnonymousCheckRule auto QA rule

---

src/Employer/Employer.Web/Configuration/ViewNames.cs
src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs
src/Provider/Provider.Web/Controllers/ManageNotificationsController.cs
src/Provider/Provider.Web/Controllers/SubmittedController.cs
src/Provider/Provider.Web/Orchestrators/ManageNotificationsOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/SubmittedOrchestrator.cs
src/Provider/Provider.Web/ViewModels/ManageNotifications/ConfirmUnsubscribeNotificationsEditModel.cs
src/Provider/Provider.Web/ViewModels/ManageNotifications/ConfirmUnsubscribeNotificationsViewModel.cs
src/Provider/Provider.Web/ViewModels/ManageNotifications/ManageNotificationsAcknowledgementViewModel.cs
src/Provider/Provider.Web/ViewModels/ManageNotifications/ManageNotificationsEditModel.cs
src/Provider/Provider.Web/ViewModels/ManageNotifications/ManageNotificationsViewModel.cs
src/Provider/Provider.Web/ViewModels/Submitted/VacancySubmittedConfirmationViewModel.cs
src/Provider/Provider.Web/Views/Dashboard/Dashboard.cshtml
src/Provider/Provider.Web/Views/ManageNotifications/ConfirmUnsubscribeNotifications.cshtml
src/Provider/Provider.Web/Views/ManageNotifications/ManageNotifications.cshtml
src/Provider/Provider.Web/Views/ManageNotifications/NotificationUnsubscribedAcknowledgement.cshtml
src/Provider/Provider.Web/Views/ManageNotifications/NotificationsUpdatedAcknowledgement.cshtml
src/Provider/Provider.Web/Views/Submitted/Confirmation.cshtml

Copy paste from employer's implementation

ER-1236 Implements manage notification view in providers

---

.editorconfig
src/Employer/Employer.Web/web.config
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/UpdateLiveVacancyCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Domain/Events/LiveVacancyClosingDateChangedEvent.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateFaaOnLiveVacancyClosingDateChanged.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/VacancyClosedEventHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/FaaService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/FaaVacancyStatusSummary.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/FaaVacancyStatuses.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/FAA/IFaaService.cs
src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/UpdateLiveVacancyCommandHandlerTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/EventHandlers/UpdateFaaOnLiveVacancyClosingDateChangedTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/EventHandlers/VacancyClosedEventHandlerTests.cs

This PR will ensure changes to a V2 vacancy closing date (or closing the vacancy) will be propagated to FAA.

ER-1049 Propagate vacancy closing date / vacancy closed to FAA

---

src/Employer/Employer.Web/Orchestrators/Part2/AboutEmployerOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/Part2/EmployerContactDetailsOrchestrator.cs
src/Employer/Employer.Web/ViewModels/Part2/AboutEmployer/AboutEmployerViewModel.cs
src/Employer/Employer.Web/ViewModels/Part2/EmployerContactDetails/EmployerContactDetailsViewModel.cs
src/Employer/Employer.Web/Views/Part2/AboutEmployer/AboutEmployer.cshtml
src/Employer/Employer.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml
src/Employer/Employer.Web/Views/Part2/Considerations/Considerations.cshtml
src/Employer/Employer.Web/Views/Part2/EmployerContactDetails/EmployerContactDetails.cshtml
src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/Employer/Employer.Web/Views/Part2/Skills/Skills.cshtml
src/Employer/Employer.Web/Views/Part2/TrainingProvider/ConfirmTrainingProvider.cshtml
src/Employer/Employer.Web/Views/Part2/TrainingProvider/SelectTrainingProvider.cshtml
src/Employer/Employer.Web/Views/Part2/VacancyDescription/VacancyDescription.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Provider/Provider.Web/Orchestrators/Part2/AboutEmployerOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/Part2/ProviderContactDetailsOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part2/AboutEmployer/AboutEmployerViewModel.cs
src/Provider/Provider.Web/ViewModels/Part2/ProviderContactDetails/ProviderContactDetailsViewModel.cs
src/Provider/Provider.Web/Views/Part2/AboutEmployer/AboutEmployer.cshtml
src/Provider/Provider.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml
src/Provider/Provider.Web/Views/Part2/Considerations/Considerations.cshtml
src/Provider/Provider.Web/Views/Part2/ProviderContactDetails/ProviderContactDetails.cshtml
src/Provider/Provider.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/Provider/Provider.Web/Views/Part2/Skills/Skills.cshtml
src/Provider/Provider.Web/Views/Part2/VacancyDescription/VacancyDescription.cshtml
src/Provider/Provider.Web/Views/VacancyPreview/VacancyPreview.cshtml

Changing the titles of part 2 pages in Employer and Provider

ER-1274 ER-1280 part 2 titles Employer & Provider

---

src/Employer/Employer.Web/Configuration/FeatureNames.cs
src/Employer/Employer.Web/Orchestrators/ManageNotificationsOrchestrator.cs
src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Employer/Employer.Web/appsettings.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json
src/Provider/Provider.Web/Configuration/FeatureNames.cs
src/Provider/Provider.Web/Orchestrators/ManageNotificationsOrchestrator.cs
src/Provider/Provider.Web/Views/Dashboard/Dashboard.cshtml
src/Provider/Provider.Web/appsettings.json
src/Shared/Recruit.Vacancies.Client/Domain/Entities/UserNotificationPreferences.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IUserNotificationPreferencesRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserNotificationPreferencesRepository.cs

In UserNotificationPreference, replaced id with idamsid.

ER-1236 ER-1214 Feature toggled notifications functionality

---

src/Employer/Employer.Web/Controllers/LegalEntityAgreementController.cs
src/Employer/Employer.Web/Orchestrators/VacancyPreviewOrchestrator.cs
src/Provider/Provider.Web/Configuration/IoC.cs
src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs
src/Provider/Provider.Web/Controllers/LegalEntityAgreementController.cs
src/Provider/Provider.Web/Controllers/VacancyPreviewController.cs
src/Provider/Provider.Web/Models/SubmitVacancyResponse.cs
src/Provider/Provider.Web/Orchestrators/LegalEntityAgreementOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/VacancyPreviewOrchestrator.cs
src/Provider/Provider.Web/ViewModels/LegalEntityAgreement/LegalEntityAgreementHardStopViewModel.cs
src/Provider/Provider.Web/Views/LegalEntityAgreement/LegalEntityAgreementHardStop.cshtml
src/Provider/Provider.Web/appsettings.json
src/Shared/Recruit.Shared.Web/Services/ILegalEntityAgreementService.cs
src/Shared/Recruit.Shared.Web/Services/LegalEntityAgreementService.cs
src/Shared/UnitTests/Shared.Web/Services/LegalEntityAgreementServiceTests.cs

We need to do a legal entity agreement check for Provider.
I have replicated the hard stop agreement check we do in employer when submitting a vacancy.  This has meant moving `LegalEntityAgreementService` from Employer into Shared.

ER-1308 - Provider legal entity agreement hard stop on vacancy submit

---

src/Employer/Employer.Web/Orchestrators/Part1/TrainingProviderOrchestrator.cs
src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml
src/Employer/Employer.Web/Views/Part1/TrainingProvider/SelectTrainingProvider.cshtml
src/Shared/Recruit.Shared.Web/TagHelpers/EsfaFeatureTagHelper.cs

ER-1294 & ER-1306 - bugfixes

---

src/Data/Recruit.ChangeScripts/010_configuration_DisabledJobs_Prod_EnableVacancyAnalyticsSummaryGenerator.js

This needs to go out with the release in the week commencing 8th July 2019

ER-1383 Enabling VacancyAnalytics Generator Job in PROD

---

src/Data/Recruit.ChangeScripts/010_vacancy_backfill_closureReason.js

Since we are introducing new field closureReason, we need to backfill this field for the existing closed vacancies. 
I am using existence of ClosedByUser field to determine if the vacancy was closed manually. There is an existing issue around this, but I am hoping that will be resolved ahead of this.

ER-1414 data update script

---

src/Provider/Provider.Web/Controllers/ErrorController.cs

Remove user claims logging from provider v2

ER-1258-Remove user claims logging from provider v2

---

src/Provider/Provider.Web/Configuration/TempDataKeys.cs
src/Provider/Provider.Web/Configuration/ViewNames.cs
src/Provider/Provider.Web/Controllers/ErrorController.cs
src/Provider/Provider.Web/Middleware/ProviderAccountHandler.cs
src/Provider/Provider.Web/ViewModels/Error/ProviderAccessRevokedViewModel.cs
src/Provider/Provider.Web/Views/Error/ProviderAccessRevoked.cshtml
src/Provider/Provider.Web/Views/Error/ProviderBlocked.cshtml
src/Shared/Recruit.Shared.Web/Views/RecruitPartialNames.cs
src/Shared/Recruit.Shared.Web/Views/Shared/_ContactDetailsListPartial.cshtml
src/Shared/Recruit.Shared.Web/Views/Shared/_GetHelpContactDetailsPartial.cshtml

I haven't used the client classes as I would like to start moving away from adding new functionality into them.

ER-1411 provider access revoked error page

---

src/QA/QA.Web/Views/BlockedOrganisations/ConfirmTrainingProviderBlocking.cshtml
src/QA/QA.Web/Views/BlockedOrganisations/ConsentForProviderBlocking.cshtml
src/QA/QA.Web/Views/BlockedOrganisations/FindTrainingProvider.cshtml
src/QA/QA.Web/Views/BlockedOrganisations/Index.cshtml
src/QA/QA.Web/Views/BlockedOrganisations/ProviderAlreadyBlocked.cshtml
src/QA/QA.Web/Views/BlockedOrganisations/ProviderBlockedAcknowledgement.cshtml
src/QA/QA.Web/Views/Dashboard/Index.cshtml
src/QA/QA.Web/Views/Reports/ApplicationsReport/Create.cshtml
src/QA/QA.Web/Views/Reports/ReportConfirmation/Confirmation.cshtml
src/QA/QA.Web/Views/Reports/ReportDashboard/Dashboard.cshtml
src/QA/QA.Web/Views/Shared/_Layout.cshtml
src/QA/QA.Web/Views/WithdrawVacancy/Acknowledgement.cshtml
src/QA/QA.Web/Views/WithdrawVacancy/AlreadyClosed.cshtml
src/QA/QA.Web/Views/WithdrawVacancy/Confirm.cshtml
src/QA/QA.Web/Views/WithdrawVacancy/Consent.cshtml
src/QA/QA.Web/Views/WithdrawVacancy/FindVacancy.cshtml
src/QA/QA.Web/wwwroot/css/application.css

Steve spotted the layout view had a zero margin, which then forced each view to have a top margin. This was fixed along with all the views. 
Fixed other style issues and content in the block provider views.

ER-1445 fix styles and content

---

src/Employer/Employer.Web/Orchestrators/CloseVacancyOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/CloseVacancyOrchestrator.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IRecruitVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs

Manual closure reason was not set.

ER-1467 Fixed closure reason for manually closed vacancies

---

src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandler.cs
src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/ProviderBlockedOnLegalEntityDomainEventHandler.cs
src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Vacancy/ProviderBlockedOnVacancyDomainEventHandler.cs
src/Shared/Recruit.Vacancies.Client/Domain/Events/ProviderBlockedOnLegalEntityEvent.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/EditVacancyInfo/LegalEntity.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/IProviderRelationshipsService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/ProviderRelationshipsService.cs

Added more logging so we can trace the request properly. 
I was not able to use the API client due to Json package version, hence carrying on using http client. 
I have not used a command from domain event handler to keep things simple, if insisted I am happy to do this once every thing has been tested locally.
Fixed error in recovering vacancies associated to the provider.  
I have done one run and it resulted in invoking some permissions. Need to create fresh data and try again.

ER-1444 invoke revoke permission api

---

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json

The config was wrongly copied under appsettings, moving it under connectionstrings.

ER-1384 Fixing QA config

---

src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Application/ApplicationSubmittedHandler.cs
src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandler.cs
src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Vacancy/VacancyReferredDomainEventHandler.cs
src/Jobs/Recruit.Vacancies.Jobs/ServiceCollectionExtensions.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/CommunicationConstants.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/EntityDataItemProviderPlugins/ApprenticeshipServiceConfigDataEntityPlugin.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/EntityDataItemProviderPlugins/ApprenticeshipServiceUrlDataEntityPlugin.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/EntityDataItemProviderPlugins/ProviderDataEntityPlugin.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/ParticipantResolverPlugins/ParticipantResolverPluginHelper.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/ParticipantResolverPlugins/ProviderParticipantsResolverPlugin.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/ParticipantResolverPlugins/VacancyParticipantsResolverPlugin.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/TemplateIdProviderPlugin.cs
src/Shared/Recruit.Vacancies.Client/Application/Communications/UserPreferencesProviderPlugin.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/VacancyClosedEventHandler.cs
src/Shared/UnitTests/Vacancies.Client/Application/Communications/ApprenticeshipServiceUrlPluginTests.cs
src/Shared/UnitTests/Vacancies.Client/Application/Communications/ParticipantResolverPluginTests.cs
src/Shared/UnitTests/Vacancies.Client/Application/Communications/TemplateIdProviderPluginTests.cs

Implemented notification for provider users. 
I had to re-instate apprenticeship url provider as it was specific to vacancy owner, I have created another config provider to allow populated values which are generic like helpdesk number.

ER-1384 Added blocked provider notification for provider

---

src/Employer/Employer.Web/Configuration/ExternalLinksConfiguration.cs
src/Employer/Employer.Web/Orchestrators/Part1/WageOrchestrator.cs
src/Employer/Employer.Web/ViewModels/Part1/Wage/WageViewModel.cs
src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml
src/Employer/Employer.Web/appsettings.json
src/Shared/Recruit.Vacancies.Client/Domain/Extensions/DateTimeExtensions.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/NationalMinimumWageProvider.cs

Updated content on wages page to provider guidance on minimum wages.

ER-1359 - wages and pay. Employer.Web

---

src/Provider/Provider.Web/Configuration/ExternalLinksConfiguration.cs
src/Provider/Provider.Web/Orchestrators/Part1/WageOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part1/Wage/WageViewModel.cs
src/Provider/Provider.Web/Views/Part1/Wage/Wage.cshtml
src/Provider/Provider.Web/appsettings.json

Updated content on wages page to provider guidance on minimum wages.

ER-1488 - wages and pay. Provider.Web

---

src/.vscode/tasks.json
src/Jobs/Recruit.Vacancies.Jobs.Tests/Recruit.Vacancies.Jobs.Tests.csproj
src/Recruit.sln

I want to write unittests for webjob handlers. So just wanted to get this project added so others can use it as well.

Add web jobs unit test project

---

src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml
src/Provider/Provider.Web/Views/Part1/Wage/Wage.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs

Some small content changes to fix issues found in QA

ER-1358 ER-1359 - Addressing QA failures.

---

src/Communication/Communication.Core/AggregateCommunicationComposeQueuePublisher.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbCommunicationRepository.cs

The queue being published to was wrong and also there was an error in the filters.

ER-1242 Fix issues in processing aggregate message

---

src/Employer/Employer.Web/Controllers/Part1/DatesController.cs
src/Employer/Employer.Web/Orchestrators/Part1/DatesOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/VacancyPreviewOrchestrator.cs
src/Employer/Employer.Web/ViewModels/Part1/Dates/DatesViewModel.cs
src/Employer/Employer.Web/Views/Part1/Dates/Dates.cshtml
src/Provider/Provider.Web/Controllers/Part1/DatesController.cs
src/Provider/Provider.Web/Orchestrators/Part1/DatesOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/VacancyPreviewOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part1/Dates/DatesViewModel.cs
src/Provider/Provider.Web/Views/Part1/Dates/Dates.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/ErrorCodes.cs
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/CustomValidators/VacancyValidators/VacancyFluentValidationExtensions.cs
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/CrossField/TrainingExpiryDateValidation.cs

Added extra validation to the Dates page to handle expiring training programmes. Also added this check to soft validations on vacancy preview.
There is also different content we show depending on whether the training has an expiry date or whether there is an error is displayed due to the training expiry date.

ER-1340 - Dates validation. Empoyer.Web

---

src/Jobs/Recruit.Vacancies.Jobs.UnitTests/ExternalSystemEventHandlers/UpdatedPermissionsExternalSystemEventHandlerTests.cs
src/Jobs/Recruit.Vacancies.Jobs.UnitTests/Jobs/TransferVacanciesFromProviderJobTests.cs
src/Jobs/Recruit.Vacancies.Jobs.UnitTests/Jobs/TransferVacancyToLegalEntityJobTests.cs
src/Jobs/Recruit.Vacancies.Jobs/ExternalSystemEventHandlers/UpdatedPermissionsExternalSystemEventsHandler.cs
src/Jobs/Recruit.Vacancies.Jobs/Jobs/TransferVacanciesFromProviderJob.cs
src/Jobs/Recruit.Vacancies.Jobs/Jobs/TransferVacancyToLegalEntityJob.cs
src/Jobs/Recruit.Vacancies.Jobs/ServiceCollectionExtensions.cs
src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/TransferVacanciesFromProviderQueueTrigger.cs
src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/TransferVacancyToLegalEntityQueueTrigger.cs
src/Shared/Recruit.Vacancies.Client/Application/Queues/Messages/TransferVacanciesFromProviderQueueMessage.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IVacancyQuery.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/IProviderRelationshipsService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/ProviderRelationshipsService.cs

From original PR https://github.com/SkillsFundingAgency/das-recruit/pull/815

ER-1486 - Transfer without LegalEntityId +smever: patch

---

src/Employer/Employer.Web/Configuration/ViewNames.cs
src/Employer/Employer.Web/Controllers/ErrorController.cs
src/Employer/Employer.Web/Exceptions/ApplicationWithdrawnException.cs
src/Employer/Employer.Web/Orchestrators/ApplicationReviewOrchestrator.cs
src/Employer/Employer.Web/Views/Error/ApplicationWithdrawn.cshtml
src/Provider/Provider.Web/Configuration/ViewNames.cs
src/Provider/Provider.Web/Controllers/ErrorController.cs
src/Provider/Provider.Web/Exceptions/ApplicationWithdrawnException.cs
src/Provider/Provider.Web/Orchestrators/ApplicationReviewOrchestrator.cs
src/Provider/Provider.Web/Views/Error/ApplicationWithdrawn.cshtml

Display a specific error page when trying to view a withdrawn vacancy

ER-1145 - Withdrawn application error page

---

src/Employer/Employer.Web/Orchestrators/Part1/TrainingProviderOrchestrator.cs
src/Employer/UnitTests/Employer.Web/Orchestrators/Part1/TrainingProviderOrchestratorTests.cs
src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/SetupProviderHandler.cs
src/Provider/Provider.Web/Controllers/ErrorController.cs
src/Provider/Provider.Web/Middleware/ProviderAccountHandler.cs
src/Provider/Provider.Web/Orchestrators/ProviderAgreementOrchestrator.cs
src/Shared/Recruit.Shared.Web/Services/TrainingProviderAgreementService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IRecruitVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/PasAccount/IPasAccountProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/PasAccount/PasAccountProvider.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProvider/TrainingProviderService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProviderSummaryProvider/TrainingProviderSummaryProvider.cs
src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs
src/Shared/UnitTests/Shared.Web/Services/TrainingProviderAgreementServiceTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Services/PasAccountProviderTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Services/TrainingProviderServiceTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Services/TrainingProviderSummaryProviderTests.cs
src/Shared/UnitTests/Vacancies.Client/TestCache.cs

Allowing the test UKPRN to skip various ukprn checks.  Also refactored to simplify Client.

ER-1477 - ESFA test training provider

---

src/Employer/Employer.Web/Views/Shared/_EditVacancyPartial.cshtml
src/Employer/Employer.Web/Views/Shared/_NonEditableVacancyDisplayPartial.cshtml
src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/Provider/Provider.Web/Views/Shared/_EditVacancyPartial.cshtml
src/Provider/Provider.Web/Views/Shared/_NonEditableVacancyDisplayPartial.cshtml
src/Provider/Provider.Web/Views/VacancyPreview/VacancyPreview.cshtml
src/QA/QA.Web/Views/Review/ReadonlyReview.cshtml
src/QA/QA.Web/Views/Review/Review.cshtml

Extend all Qualifications preview sections to occupy full page width

ER-936 extend qualifications client width +semver:patch

---

src/Communication/Communication.UnitTests/Communication.UnitTests.csproj
src/Employer/Employer.Web/Employer.Web.csproj
src/Employer/IntegrationTests/IntegrationTests.csproj
src/Employer/UnitTests/UnitTests.csproj
src/Jobs/Recruit.Vacancies.Jobs.UnitTests/Recruit.Vacancies.Jobs.UnitTests.csproj
src/Jobs/Recruit.Vacancies.Jobs/Recruit.Vacancies.Jobs.csproj
src/Provider/Provider.Web/Provider.Web.csproj
src/Provider/UnitTests/UnitTests.csproj
src/QA/QA.Web/QA.Web.csproj
src/QA/UnitTests/UnitTests.csproj
src/Shared/Recruit.Shared.Web/Recruit.Shared.Web.csproj
src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj
src/Shared/UnitTests/UnitTests.csproj

I have put particular regression test points relating to this upgrade in the JIRA ticket https://skillsfundingagency.atlassian.net/browse/ER-1374

ER-1374 📦⬆ - General sweep of safe package upgrades

---

src/Employer/Employer.Web/Orchestrators/Part1/EmployerOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/Part1/LocationOrchestrator.cs
src/Employer/UnitTests/Employer.Web/Services/LegalEntityAgreementServiceTests.cs
src/Jobs/Recruit.Vacancies.Jobs.UnitTests/Triggers/QueueTriggers/DeleteStaleQueryStoreDocumentsQueueTriggerTests.cs
src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/DeleteStaleQueryStoreDocumentsQueueTrigger.cs
src/Provider/Provider.Web/Orchestrators/Part1/LocationOrchestrator.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/Vacancy.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/IQueryStoreReader.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/EditVacancyInfo/EmployerEditVacancyInfo.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStoreClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/EmployerAccount/EmployerAccountProvider.cs
src/Shared/UnitTests/Shared.Web/Services/LegalEntityAgreementServiceTests.cs
src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/CloneVacancyCommandHandlerTests.cs

There are no unit tests and unfortunately the implementation of Utility has made it very difficult. We should have a tech debt to refactor utility to implement an interface to enable unit testing.

CON-1184 populate account legal entity public hashed id on vacancy

---

src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/BeginMigrationQueueTrigger.cs
src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/PerformDataMigrationQueueTrigger.cs
src/Shared/Recruit.Vacancies.Client/Application/Queues/Messages/DataMigrationQueueMessage.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Slack/SlackClient.cs

- Reverted back to queues.
- Added delay in lining up the vacancies. 
- Added retries after incremental delays for each failed message.

CON-1185 added delay and retries

---

azure/template.json

Added Provier App insight  insturmentation key to app service

---

src/Employer/Employer.Web/Views/Part1/Training/TrainingHelp.cshtml
src/Employer/Employer.Web/Views/Part2/Considerations/Considerations.cshtml
src/Employer/Employer.Web/Views/Part2/EmployerContactDetails/EmployerContactDetails.cshtml
src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/ContactDetailValidator.cs

Grouped recruit tickets for testing
- CON-2039
- CON-2040
- CON-2041
- CON-2090

Recruit tickets

---

src/Employer/Employer.Web/Views/CloneVacancy/CloneVacancyDatesQuestion.cshtml
src/Shared/Recruit.Shared.Web/ViewModels/InfoMessages.cs
src/Shared/Recruit.Shared.Web/ViewModels/ValidationMessages.cs

Updates content on clone advert page

[CON-2088] Clone advert content

---

src/Employer/Employer.Web/Views/Part2/AboutEmployer/AboutEmployer.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs

Updates page title, cancel link position and error message

[CON-2069] Page title and cancel button

---

src/Employer/Employer.Web/Views/ManageNotifications/NotificationsUpdatedAcknowledgement.cshtml

Changes heading content and adds additions options for displaying what changes the users has made using sentences in some scenarios instead of a single bullet point.

CON-2075 Email notifications updated confirmation page

---

src/API/Recruit.Api.UnitTests/Controllers/ReferenceDataControllerTests.cs
src/API/Recruit.Api.UnitTests/Queries/WhenGettingSkillsReferenceData.cs
src/API/Recruit.Api/Controllers/ReferenceDataController.cs
src/API/Recruit.Api/Queries/GetSkillsQuery.cs
src/API/Recruit.Api/Queries/GetSkillsQueryHandler.cs
src/API/Recruit.Api/Queries/GetSkillsQueryResponse.cs

Add new reference data controller with candidate skills endpoint

FAI-74 add skills endpoint

---

azure-pipelines.yml
pipeline-templates/job/deploy.yml

Speed up deployment by deploying the 3 web apps in parallel after worker and API
Use DAS - Continuous Deployment Agents agent pool for deploying apps

DASD-9098 Parallel Deployments

---

azure-pipelines.yml

das-platform-building-blocks: 0.4.26 to 0.4.29
das-platform-automation: 4.5.9 to 4.5.11
Added deployment condition to stages

azure-pipelines.yml: Updated repository refs to latest for improved wait-azure-devops-deployment step

---

src/Provider/Provider.Web/Orchestrators/Part1/DurationOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part1/Duration/DurationViewModel.cs
src/Provider/Provider.Web/Views/Part1/Duration/Duration.cshtml

Validation and documentation already 250 characters

Fai 334 duration working hours content

---

src/Provider/Provider.Web/Orchestrators/Part1/WageOrchestrator.cs
src/Provider/Provider.Web/ViewModels/Part1/Wage/WageViewModel.cs
src/Provider/Provider.Web/Views/Part1/Wage/Wage.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs

API documentation already has character limit

Fai 323 pay rate content

---

src/Provider/Provider.Web/Views/Part1/Title/Title.cshtml
src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/TitleValidationTests.cs

Story includes limiting text to 100 characters but it already is limited at 100

FAI-318-Update content

---

src/Provider/Provider.Web/Views/Vacancies/Vacancies.cshtml

Checked with Ellen and changes are for traineeship and apprenticeship except for the table

Fai 399 draft vacancies content

---

src/Provider/Provider.Web/Views/Vacancies/Vacancies.cshtml
src/Provider/Provider.Web/Views/VacancyCheckYourAnswers/CheckYourAnswers.cshtml

- Add proofread reminder to check your answers page 
- Update WorkingWeekDescription label and hide WorkingWeekHours for Traineeships on check your answers page

Fai 528 reminder message

---

src/Provider/Provider.Web/Views/VacancyManage/ManageVacancy.cshtml

Updated closed banner on the Manage page

FAI-526-Updated closed banner on the Manage page

---

src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/CloseExpiredVacanciesCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IVacancyQuery.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateEmployerDashboardOnChange.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateProviderDashboardOnChangeEventHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs
src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/CloseExpiredVacanciesCommandHandlerTests.cs

Changed so that the query now filters on the dates and status, and also has paging

FAI-550 - Add paging and filtering to closed expired vacancy handler

---

src/Provider/Provider.Web/Controllers/DeleteVacancyController.cs
src/Provider/Provider.Web/Orchestrators/DeleteVacancyOrchestrator.cs
src/Provider/Provider.Web/ViewModels/DeleteVacancy/DeleteViewModel.cs
src/Provider/UnitTests/Provider.Web/Controllers/DeleteVacancyControllerTests.cs
src/Provider/UnitTests/Provider.Web/Orchestrators/DeleteVacancyOrchestratorTests/WhenPostingDeleteVacancy.cs
src/Shared/Recruit.Shared.Web/ViewModels/InfoMessages.cs

Updated content on delete vacancy

FAI-525-Updated content on delete vacancy

---

src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs
src/Employer/Employer.Web/Orchestrators/VacancyViewOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/VacancyManageOrchestrator.cs
src/Provider/Provider.Web/Orchestrators/VacancyViewOrchestrator.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IApplicationReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IRecruitVacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/VacancyApplications/VacancyApplication.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/QueryStore/WhenConvertingFromApplicationReviewToVacancyApplication.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Services/VacancyClientGetVacancyApplications.cs

Fix issue with applications not showing for vacancies. This removes the need for the query view

FAI-556 applications not showing bug

---

src/Provider/Provider.Web/Controllers/VacancyCheckYourAnswersController.cs
src/Provider/Provider.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs
src/Provider/Provider.Web/Views/VacancyCheckYourAnswers/CheckYourAnswers.cshtml

Update Check your answers page to show vacancy cloned message

FAI-461 FAI-460

---

src/Provider/Provider.Web/Controllers/Part1/LegalEntityAndEmployerController.cs
src/Provider/Provider.Web/Views/VacancyTaskList/ProviderTaskList.cshtml

For single account legal entity option then the wrong account id was being used

FAI-689 - Correct issue with wrong accountid being used

---

src/API/Recruit.Api.UnitTests/Commands/WhenCreatingTraineeshipVacancy.cs
src/API/Recruit.Api.UnitTests/Commands/WhenCreatingVacancy.cs
src/API/Recruit.Api.UnitTests/Mappers/VacancyMapperTests.cs
src/API/Recruit.Api/Commands/CreateVacancyCommandHandler.cs
src/API/Recruit.Api/Mappers/VacancyMapper.cs
src/API/Recruit.Api/Models/CreateVacancyRequest.cs

Story Link: https://skillsfundingagency.atlassian.net/browse/FAI-763
AS A provider / employer or Third party
I WANT to be able to add up to two additional questions as part of the vacancy SO THAT I can get applicants to answer specific questions to help with recruitment

Add Additional Questions to the APIs - CreateVacancyRequest

---

src/Provider/Provider.Web/Controllers/Part1/TitleController.cs
src/Provider/Provider.Web/Orchestrators/Part1/TitleOrchestrator.cs
src/Provider/UnitTests/Provider.Web/Controllers/Part1/TitleControllerTests.cs

Corrected redirect for if its a traineeship

FAI-767 - Correct issue with not being able to create traineeship

---

src/Shared/Recruit.Shared.Web/Recruit.Shared.Web.csproj
src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj

Updated SFA.DAS.VacancyServices.Wage nuget package to version 1.0.30 in Recruit.Shared.Web and Recruit.Vacancies.Client

FAI-765 FAI-766 Updated SFA.DAS.VacancyServices.Wage nuget package

---

src/Provider/Provider.Web/Configuration/ConfigurationExtensions.cs
src/Provider/Provider.Web/Provider.Web.csproj
src/Provider/Provider.Web/Startup.ConfigureServices.cs

Story: https://skillsfundingagency.atlassian.net/browse/FAI-735
Commit: 
Included Change Sign in details link in the navigation menu based on the UseDfESignIn Toggle configuration

Story: https://skillsfundingagency.atlassian.net/browse/FAI-735

---

src/Employer/Employer.Web/AppStart/EmployerAccountPostAuthenticationClaimsHandler.cs
src/Employer/Employer.Web/Authorization/RouteValueKeys.cs
src/Employer/Employer.Web/Configuration/ConfigurationExtensions.cs
src/Employer/Employer.Web/Controllers/VacancyCheckYourAnswersController.cs
src/Employer/Employer.Web/Controllers/VacancyManageController.cs
src/Employer/Employer.Web/Controllers/VacancyPreviewController.cs
src/Employer/Employer.Web/Controllers/VacancyTaskListController.cs
src/Employer/Employer.Web/Interfaces/IEmployerAccountAuthorizationHandler.cs
src/Employer/Employer.Web/Middleware/EmployerAccountAuthorisationHandler.cs
src/Employer/Employer.Web/Middleware/EmployerAccountOwnerAuthorizationHandler.cs
src/Employer/Employer.Web/Middleware/EmployerAccountOwnerRequirement.cs
src/Employer/Employer.Web/Middleware/EmployerUserRole.cs
src/Employer/Employer.Web/Middleware/PolicyNames.cs
src/Employer/Employer.Web/Models/EmployerUserAccountItem.cs
src/Employer/Employer.Web/Models/EmployerUserAccounts.cs
src/Employer/Employer.Web/Startup.ConfigureServices.cs
src/Employer/Employer.Web/Views/Error/AccessDenied.cshtml
src/Employer/Employer.sln
src/Employer/UnitTests/Employer.Web/AppStart/WhenHandlingEmployerAccountOwnerRoleAuthorizationHandler.cs

Commit Details:
Introducing new Role based permission for Vacancy Create Page and Edit Page.
Story: https://skillsfundingagency.atlassian.net/browse/FAI-802

FAI-802 Block "View only" users from making changes in RAAv2

---

src/QA/QA.Web/Configuration/ServiceCollectionExtensions.cs
src/QA/QA.Web/Controllers/DashboardController.cs
src/QA/QA.Web/Controllers/HomeController.cs
src/QA/QA.Web/QA.Web.csproj

Commit Details
1. Updated the DfESignIn Nuget Package
2. Start page logic behind DfESignIn Toggle switch value
3. Testing feedback changes
Story: 
https://skillsfundingagency.atlassian.net/browse/FAI-841

FAI-841 DSI package update

---

azure/template.json
src/Provider/Provider.Web/Controllers/ErrorController.cs
src/Provider/Provider.Web/ViewModels/Error/Error403ViewModel.cs
src/Provider/Provider.Web/Views/Error/AccessDenied.cshtml
src/Provider/Provider.Web/appsettings.json
src/Provider/UnitTests/Provider.Web/ViewModels/Error/WhenBuildingError403ViewModel.cs

403 Forbidden Error Page with content relevant to DfESignIn
https://skillsfundingagency.atlassian.net/browse/FAI-906

FAI-906_Recruit_Amend_Access_Denied_Page

---

src/QA/QA.Web/Configuration/ServiceCollectionExtensions.cs
src/QA/QA.Web/Controllers/DashboardController.cs
src/QA/QA.Web/Controllers/HomeController.cs
src/QA/QA.Web/QA.Web.csproj
src/QA/QA.Web/Startup.ConfigureServices.cs
src/QA/QA.Web/ViewModels/Home/HomeIndexViewModel.cs
src/QA/QA.Web/Views/Home/Index.cshtml
src/QA/QA.Web/appsettings.json
src/QA/UnitTests/Qa.Web/Controllers/DashboardControllerTest.cs
src/QA/UnitTests/Qa.Web/Controllers/HomeControllerTest.cs

Commit Details:
Included the Latest DfeSignIn Nuget Package.
Other improvements and tidy up in the code.
Story: https://skillsfundingagency.atlassian.net/browse/FAI-772

FAI-772 DfESignIn Pkg update with Signout Redirect Issue Fixed

---

src/Provider/Provider.Web/Configuration/ConfigurationExtensions.cs
src/Provider/Provider.Web/Middleware/TrainingProviderAllRolesAuthorizationHandler.cs
src/Provider/Provider.Web/Middleware/TrainingProviderAllRolesRequirement.cs
src/Provider/Provider.Web/Middleware/TrainingProviderAuthorizationHandler.cs
src/Provider/Provider.Web/Provider.Web.csproj
src/Provider/Provider.Web/Startup.ConfigureServices.cs
src/Provider/Provider.Web/appsettings.json
src/Provider/UnitTests/Provider.Web/Middleware/WhenHandlingTrainingProviderAllRolesRequirement.cs
src/Provider/UnitTests/Provider.Web/Middleware/WhenHandlingTrainingProviderAuthorization.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/GetProviderStatusDetails.cs
src/Shared/Recruit.Vacancies.Client/Domain/Entities/ProviderAccountResponse.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IGetProviderStatusClient.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/OuterApiGetProviderStatusClient.cs
src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs
src/Shared/UnitTests/Vacancies.Client/Domain/Entities/WhenBuildingGetProviderAccountRequest.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Client/OuterApiGetProviderStatusClientTest.cs

Commit Details:
Added new Requirement to the Policy to check if the Provider is valid one. Condition 1: is the provider's profile a Main or Employer Profile. Condition 2: is the provider's status Active or On-boarding.
Story: https://skillsfundingagency.atlassian.net/browse/FAI-954

Fai 954 provider Recruit create shut out page

---

src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs
src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/ClosingDateValidationTests.cs

This reverts commit b243010d94dea9bd00ed0d6a8accb54a554c8770 which was for FAI-1005

FAI-1008 - Change closing date validation to be 14 days

---

src/Employer/Employer.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Employer/Employer.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs
src/Employer/Employer.Web/Views/Shared/_vacancyApprenticeshipPreview.cshtml
src/Provider/Provider.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Provider/Provider.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs
src/Provider/Provider.Web/Views/Shared/_vacancyApprenticeshipPreview.cshtml
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApplicationReviewCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApplicationReviewsCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/OuterApi/Requests/PostApplicationStatusRequest.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/VacancyApplications/VacancyApplication.cs

Also stop sending updates to candidates where the status is not successful or unsuccesful

FAI-1255 FAI-1256 - Update request to update application

---

src/Employer/Employer.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Employer/Employer.Web/ViewModels/DisplayVacancyViewModel.cs
src/Employer/Employer.Web/Views/Shared/_vacancyApprenticeshipPreview.cshtml
src/Provider/Provider.Web/Mappings/VacancyDisplayViewModelMapper.cs
src/Provider/Provider.Web/ViewModels/DisplayVacancyViewModel.cs
src/Provider/Provider.Web/Views/Shared/_vacancyApprenticeshipPreview.cshtml

Fixes a null reference exception being thrown when the employer or provider has opted not to add any qualifications

FAI-2030 - Fix preview screens when no qualifications on advert

---

src/Employer/Employer.Web/Views/ApplicationReview/ApplicationReviewV2.cshtml

story: https://skillsfundingagency.atlassian.net/browse/FAI-2166

FAI-2166 Back button fix and content change for the Application review page

---

src/Provider/Provider.Web/Views/ApplicationReview/ApplicationReviewV2.cshtml

Content should only show when the employer has said they want to interview

FAI-2282 - Remove content when not at correct status

---

src/Employer/Employer.Web/ViewModels/ApplicationReviews/ApplicationReviewsFeedbackViewModel.cs
src/Employer/UnitTests/Employer.Web/Controllers/ApplicationReviewsControllerTests.cs
src/Provider/Provider.Web/Views/ApplicationReviews/ApplicationReviewsToUnsuccessfulFeedback.cshtml
src/Shared/Recruit.Shared.Web/ViewModels/InfoMessages.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApplicationReviewsCommandHandler.cs

Change so that emails and feedback are only sent to the candidates once

FAI-2258 - Update multiple application statuses

---

src/Provider/Provider.Web/Orchestrators/VacanciesOrchestrator.cs
src/Provider/UnitTests/Provider.Web/Orchestrators/Vacancies/SearchResultHeaderTest/SearchResultHeaderTestBase.cs
src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/UserSignedInCommandHandler.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserNotificationPreferencesRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserRepository.cs

Make user id search case insensitive

FAI-2315 - Make user id search case insensitive

---

src/Employer/Employer.Web/Orchestrators/ApplicationReviewOrchestrator.cs
src/Employer/Employer.Web/ViewModels/ApplicationReview/ApplicationReviewViewModel.cs
src/Employer/Employer.Web/Views/ApplicationReview/ApplicationReview.cshtml
src/Employer/Employer.Web/Views/ApplicationReview/ApplicationReviewV2.cshtml
src/Provider/Provider.Web/Orchestrators/ApplicationReviewOrchestrator.cs
src/Provider/Provider.Web/ViewModels/ApplicationReview/ApplicationReviewViewModel.cs
src/Provider/Provider.Web/Views/ApplicationReview/ApplicationReview.cshtml
src/Provider/Provider.Web/Views/ApplicationReview/ApplicationReviewV2.cshtml
src/Shared/Recruit.Vacancies.Client/Domain/Extensions/AddressExtensions.cs
src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IApplicationReviewRepository.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ApplicationReview/ApplicationReviewService.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ApplicationReview/Requests/GetApplicationReviewByIdApiRequest.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ApplicationReview/Responses/ApplicationReview.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ApplicationReview/Responses/GetApplicationReviewByIdApiResponse.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/ApplicationReview/Responses/GetApplicationReviewsByVacancyReferenceApiResponse.cs
src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
src/Shared/UnitTests/Shared.Web/Extensions/AddressExtensionsTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/ApplicationReview/ApplicationReviewServiceTests.cs
src/Shared/UnitTests/Vacancies.Client/Infrastructure/Client/VacancyClientTests..cs

✨ Add Candidate Applied Locations feature
- Introduced `CandidateAppliedLocations` in `ApplicationReviewViewModel`.
- Updated `GetApplicationReviewViewModelAsync` to populate new property.
- Added `SplitCitiesToList` extension method for city name handling.
- Modified Razor views to display candidate's applied locations.
- Enhanced unit tests for new functionality and cleaned up code.

FAI-2409 Update Application form in RAA with locations applied

---

src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs

This was toggle to get from outer api which was incorrect

FAI-2657 - Correct count for employer review

---

src/Employer/Employer.Web/Controllers/VacancyManageController.cs
src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs
src/Employer/Employer.Web/Views/Shared/_VacancyApplicationsTablePartial.cshtml
src/Employer/Employer.Web/Views/Shared/_VacancySharedApplicationsTablePartial.cshtml
src/Employer/Employer.Web/wwwroot/css/app.css
src/Provider/Provider.Web/Controllers/VacancyManageController.cs
src/Provider/Provider.Web/Orchestrators/VacancyManageOrchestrator.cs
src/Provider/Provider.Web/Views/Shared/_VacancyApplicationsTablePartial.cshtml
src/Provider/Provider.Web/wwwroot/css/app.css

✨ Update locationFilter default value to "All"
- Change default value of locationFilter in controllers and orchestrators.
- Update filtering logic for applications based on new default value.
- Modify HTML dropdown options to replace empty with "All locations".
- Enhance CSS for better styling of error messages and elements.
- Ensure consistency across view models and partial views.

FAI-2722 Bug Hot Fix ML Location Filter Null Exception
