src/Employer.Web/Configuration/ExternalLinksConfiguration.cs, src/Employer.Web/Configuration/IoC.cs, src/Employer.Web/Configuration/ManageApprenticeshipsLinkHelper.cs, src/Employer.Web/Configuration/ManageApprenticeshipsRoutes.cs, src/Employer.Web/Configuration/RouteNames.cs, src/Employer.Web/Controllers/ExternalLinksController.cs, src/Employer.Web/Startup.ConfigureServices.cs, src/Employer.Web/Views/Shared/_Layout.cshtml, src/Employer.Web/appsettings.Development.json, src/Employer.Web/appsettings.json, src/Esfa.Recruit.Azure.Resources/azuredeploy.json, src/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json
Pulled out the routes for employer links into separate config.
@EwanNoble I've added 2 new config values that will need adding to the release definition:
**ExternalLinks:ManageApprenticeshipSiteUrl** - This is the base url for the MA site for each environment. e.g. https://test-eas.apprenticeships.sfa.bis.gov.uk
**ExternalLinks:EmployerIdamsSiteUrl** - This is the base url for Idams for each environment. e.g. https://test-login.apprenticeships.sfa.bis.gov.uk
=> External links

src/Employer/Employer.Web/Employer.Web.csproj
Updated to double cover us from [Microsoft Security Advisory CVE-2018-0787: ASP.NET Core Elevation Of Privilege Vulnerability](https://github.com/aspnet/Announcements/issues/295)
Article says that "Apps hosted in Azure Web Apps are not susceptible to this vulnerability." but the code fix is simple for us anyway.
=> Updated project references to fix security flaw

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json
I don't think you can specify creation of a storage account queue in ARM templates yet. 😫  @EwanNoble would this be okay.
The consuming code creates a queue if it does not already exist so we shouldn't encounter any issues.
=> Update for Storage account connections string used by EditVacancyInfo job and queue event

setup/containers/docker-compose.yml, src/Employer/Employer.Web/Program.cs, src/QA/QA.Web/Program.cs
Hi, I don't think the changes in this pull request would adversely affect anyone else running the solutions and using Docker for local dependencies. For me it will make a difference as it will allow me to use the local Redis container dependencies for logging without having to change appSettings.json constantly and having to exclude committing it.
Also the `docker-compose.yaml` change makes it easier for me to run an elastic v5 + container without configuring the virtual page memory on the virtual Docker host frequently. Elastic search requires 4GB.
=> Docker compose change and env config

src/Jobs/Recruit.Vacancies.Jobs/DashboardGenerator/DashboardCreator.cs, src/Jobs/Recruit.Vacancies.Jobs/DashboardGenerator/DashboardGeneratorJob.cs, src/Jobs/Recruit.Vacancies.Jobs/Program.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateDashboardOnVacancyChange.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Events/QueueNames.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/DashboardService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/IDashboardService.cs, src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs
This is a very basic job. I have used an inner class for the message at the moment as it is not event driven and just to keep it simple. This is a job that will change soon after private beta.
An example message to be published manually onto the queue can be:
```
{
"EmployerAccountId": "MYJR4X"
}
```
=> ER-499 job to rebuild employer dashboard

src/Jobs/Recruit.Vacancies.Jobs/VacancyStatus/LiveVacancyStatusInspector.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbExtensions.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs
A work around for the queryViews collection to allow us to delete the collection in environments allow the release process to create and not the webjob auto creating it.
=> Add check for existence of queryViews collection

src/Employer/Employer.Web/Controllers/ErrorController.cs, src/Jobs/Recruit.Vacancies.Jobs/ApprenticeshipProgrammes/ApprenticeshipProgrammesJob.cs, src/Jobs/Recruit.Vacancies.Jobs/ApprenticeshipProgrammes/ApprenticeshipProgrammesUpdater.cs, src/Jobs/Recruit.Vacancies.Jobs/DashboardGenerator/DashboardCreateMessage.cs, src/Jobs/Recruit.Vacancies.Jobs/DashboardGenerator/DashboardGeneratorJob.cs, src/Jobs/Recruit.Vacancies.Jobs/EditVacancyInfo/EditVacancyInfoJob.cs, src/Jobs/Recruit.Vacancies.Jobs/Recruit.Vacancies.Jobs.csproj, src/Jobs/Recruit.Vacancies.Jobs/VacancyEvents/VacancyEventHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/VacancyEvents/VacancyEventsJob.cs, src/Jobs/Recruit.Vacancies.Jobs/VacancyReviewEvents/VacancyReviewEventHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/VacancyReviewEvents/VacancyReviewEventsJob.cs, src/Jobs/Recruit.Vacancies.Jobs/VacancyStatus/VacancyStatusJob.cs, src/Jobs/Recruit.Vacancies.Jobs/nlog.config, src/QA/QA.Web/Controllers/ErrorController.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbCollectionBase.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/SequenceStore/MongoSequenceStore.cs, src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj
- Updated logging to resolve issues highlighted in Gorilla testing session.
- Added retry logic to repo/store classes in the event of a MongoCommandException. 
There is a knock-on effect of the retry logic for the jobs, in that if they pick messages off of queues they could retry up to 15 times.
5 (times message retried) **x** 3 (Polly retries)
=> ER-509 - Logging update & retry policy

src/QA/QA.Web/nlog.config
This is something that maybe temporary while we have internal QA users to help monitor which users experience which errors on the QA site. Maybe remove it for public beta.
=> Including the QA user in the logs

src/Employer/Employer.Web/Orchestrators/SubmittedOrchestrator.cs
Review might have been created that will have updated the vacancy status before the redirect to the confirmation page has happened.
=> ER-572: Hotfix - Add check for PendingReview

src/Employer/Employer.Web/Configuration/ConfigurationExtensions.cs, src/Employer/Employer.Web/Configuration/CookieNames.cs, src/Employer/Employer.Web/Middleware/EmployerAccountHandler.cs, src/Employer/Esfa.Recruit.Azure.Resources/Esfa.Recruit.Azure.Resources.deployproj, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json, src/Employer/Esfa.Recruit.Azure.Resources/deployments/app-service-resources.json, src/QA/QA.Web/Configuration/CookieNames.cs, src/QA/QA.Web/Configuration/ServiceCollectionExtensions.cs
One thing I noticed after while doing this PR and giving cookies unique names between the two sites is I could run the employer app and the qa app in the same browser without conflicts in cookie resolution.
=> ER-515 renaming cookies and turning off arr affinity cookie

src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/ValidationConstants.cs, src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/TitleValidationTests.cs
Note that you can create a vacancy with the title being `apprentice`. This is valid and is what we allow on RAA V1 and the vacancy API.
=> ER-565 - Vacancies must contain the word 'apprentice' or 'apprenticeships' in the title.

src/Employer/Employer.Web/Extensions/ApplicationReviewExtensions.cs, src/Shared/Recruit.Vacancies.Client/Domain/Entities/Application.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateVacancyApplicationsOnApplicationReviewChange.cs
Its possible to create an application in FAA without specifying any preference for disability status.  So we need to handle `null` values.
I didn't want to default this value to `Unknown` as I wanted to accurately represent what is passed in from FAA. Instead if this value is null then we'll display `Unknown` where appropriate.
=> ER-580 - Allowing DisabilityStatus to be null

src/.vscode/launch.json
This is so that the `launch.json` used by vs code can still be checked in for configurations but launching employer web can be specific for each user.
@leewadhams I just added `export EmployerAccount=MYJR4X` to the bottom of my `.bash_profile`
Will update the developer setup confluence page
=> Making launch url for the employer web project use the employer account id set in an env variable.

src/Data/Recruit.ChangeScripts/010-queryViews_MigrateDocuments_queryStore.js
Ignoring old Dashboard and ApprenticeshipProgrammes docs from being copied over to new QueryStore
=> Ignore old documents

src/.vscode/settings.json, src/Employer/Employer.Web/Controllers/Part2/SkillsController.cs, src/Employer/Employer.Web/Orchestrators/Part2/SkillsOrchestrator.cs, src/Employer/Employer.Web/ViewModels/Part2/Skills/SkillsViewModel.cs, src/Employer/Employer.Web/Views/Part2/Skills/Skills.cshtml, src/Employer/UnitTests/Employer.Web/Orchestrators/Part2/SkillOrchestratorTests.cs
There may well be a much simpler/better way to do this.
To retain ordering of the custom skills entered before they are saved I've introduced an order number for them. It surfaces as a prefix of the `value` on the checkbox `e.g. 1-Programming Ability`
=> ER-667 custom skills added as checkboxes

src/Employer/Employer.Web/ViewModels/DashboardViewModel.cs, src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml, src/QA/QA.Web/Controllers/ReviewController.cs, src/QA/QA.Web/Orchestrators/ReviewOrchestrator.cs, src/QA/QA.Web/TagHelpers/EsfaReviewCheckboxTagHelper.cs, src/QA/QA.Web/ViewModels/ReviewEditModel.cs, src/QA/QA.Web/ViewModels/ReviewViewModel.cs, src/QA/QA.Web/ViewModels/Validations/ReviewEditModelValidator.cs, src/QA/QA.Web/Views/Review/Review.cshtml, src/Shared/Recruit.Shared.Web/Extensions/EnumExtensions.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApproveVacancyReviewCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ReferVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ReferVacancyReviewCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/ApproveVacancyReviewCommand.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/ReferVacancyReviewCommand.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/VacancyReviewValidator.cs, src/Shared/Recruit.Vacancies.Client/Domain/Entities/VacancyReview.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IQaVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/QaVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateEmployerDashboardOnChange.cs
Checkboxes on the QA Review screen are now driven by an array of 'field identifiers' and not individual ViewModel properties. This makes the persisting of field identifiers to the review entity simpler.
=> ER-454 Vacancy rejection

src/Employer/Employer.Web/Controllers/VacancyPreviewController.cs, src/Employer/Employer.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs, src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml
The issue here is that there was an assumption that if a section is invalid then the button will always be an `Edit`.  A section can be invalid due to missing information so the button for an invalid section should be either `Add` or `Edit` depending on the issue.
I've introduced a new state for the section called `InvalidIncomplete`. So we can show an `Edit` button should the section be `Invalid` or an `Add` button if it is `InvalidIncomplete`.
We previously had two functions to set the state depending on whether it is a GET or POST. I've now simplified this to a single function.
=> ER-545 - Part 2 Add buttons turning to edits

src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json
Test this in AT. Default without setting the value in VSTS is 180. You can override it by passing the parameter in to the resource group deployment.
=> Added VacancyReviewAssignationTimeoutMinutes to ARM template

src/Employer/Employer.Web/Configuration/IoC.cs, src/Employer/Employer.Web/Mappings/ReviewFieldIndicatorMapper.cs, src/Employer/Employer.Web/Mappings/ReviewFieldMappingLookups.cs, src/Employer/Employer.Web/Mappings/ReviewFieldMappingLookupsForPage.cs, src/Employer/Employer.Web/Orchestrators/Part1/EmployerOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part1/ShortDescriptionOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part1/TitleOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part1/TrainingOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part1/WageOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/AboutEmployerOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/ApplicationProcessOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/ConsiderationsOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/EmployerContactDetailsOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/QualificationsOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/SkillsOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/TrainingProviderOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part2/VacancyDescriptionOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/VacancyPreviewOrchestrator.cs, src/Employer/Employer.Web/Services/IReviewSummaryService.cs, src/Employer/Employer.Web/Services/ReviewSummaryService.cs, src/Employer/Employer.Web/ViewModels/VacancyPreview/ReviewFieldIndicatorViewModel.cs, src/Employer/Employer.Web/Views/Shared/_ReviewSummary.cshtml, src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml, src/QA/QA.Web/Views/Review/UnassignReview.cshtml, src/Shared/Recruit.Vacancies.Client/Domain/Entities/VacancyReview.cs
- Hooks into same code as manual qa indicators
**Note:** There is an outstanding task to make the field names contained in the messages 'friendly' as you get things like _EmployerAddress_ (all one word) at the moment, along with names that don't match the on screen text. Possible solution is to introduce a ```FieldDisplayName``` property into the ```ReviewFieldIndicatorViewModel``` class and use that to replace values in tokenised message texts added to the ```Texts``` property.
=> ER-671 Display Auto QA Errors in Employer site

src/QA/QA.Web/Controllers/DashboardController.cs
Bug fix. 
If the session has timed out and the 'Review First Vacancy' button is clicked then the authentication callback fails as there isn't a corresponding GET for the POST and it causes an error.  So I've added a GET which will handle the callback.
=> ER-453 - Handling authentication callback on 'Review First Vacancy' POST

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/BannedPhrases.json, src/Data/CosmosDb/Console.RecruitSeedDataWriter/SeedScript.ps1
- This PR also covers ER-711 which is also an earlier update to the banned phrase list.
- Removal of flag in .ps file that was causing reference data to be replaced instead of skipped. Default without flag if to skip if reference data exists.
=> ER 746 update banned phrases

src/Data/CosmosDb/Configuration.json
Reducing the initial RU values for the collections that don't have a shard key.
We have a story for DevOps to make this configurable but talking to Steve yesterday he doesn't think it's going to be easy to do.
We'll therefore need to manually set the RU's in the environments. For our Dev ones we can just default to the lowest value to keep costs down.
=> Reduce initial RU value for un-paritioned collections

src/QA/QA.Web/Orchestrators/ReviewOrchestrator.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApproveVacancyReviewCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ReferVacancyReviewCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/ApproveVacancyReviewCommand.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/ReferVacancyReviewCommand.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IQaVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/QaVacancyClient.cs
Fixing a gap in the automated QA Web stories.  In QA Web the selected auto QA checkboxes were not being persisted so all the failed QA checks were being shown in Employer Web not just the selected ones.
=> ER-651 - Persisting selected automated QA rules

src/Employer/Employer.Web/Orchestrators/DashboardOrchestrator.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
From the conversation with @mgwilliam and @sachpatel have added some safety around getting dashboard.
- If user navigates to the dashboard page and it's missing then it'll generate.
- Occurrence of this scenario should be limited now we've got the re-generate Dashboard job but this has been added for safety.
=> Generate Dashboard if not available

src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/IQueryStore.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStoreClient.cs
Recreate method in Mongo Query Store didn't account for no new items. It is required that we still delete any existing items. The item type cannot be derived from items in case there are no new ones, hence added typename as parameter.
=> Fixes issue with recreate method in mongo query store

src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/DomainEventsJob.cs, src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Application/ApplicationWithdrawnHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Candidate/DeleteCandidateHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/Program.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/DeleteApplicationReviewsCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/DeleteApplicationReviewsCommand.cs, src/Shared/Recruit.Vacancies.Client/Domain/Events/ApplicationReviewDeletedEvent.cs, src/Shared/Recruit.Vacancies.Client/Domain/Events/CandidateDeleteEvent.cs, src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IApplicationReviewRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IJobsVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateEmployerDashboardOnChange.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateVacancyApplicationsOnApplicationReviewChange.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventStore/QueueNames.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbApplicationReviewRepository.cs
Hard deletes all data regarding a candidate.
Is triggered by a candidate deleting themselves from FAA.
FAA calls the legacy client which drops a message onto the `candidate-delete-queue` queue.
For each applicationReview deleted a `ApplicationReviewDeletedEvent` event is raised which rebuilds the relevant projections.
=> ER-757 - Delete candidate data

src/Employer/Employer.Web/Services/ReviewSummaryService.cs, src/Employer/Employer.Web/ViewModels/ReviewSummaryViewModel.cs, src/Employer/Employer.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs, src/Employer/Employer.Web/Views/Shared/_ReviewSummary.cshtml, src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml, src/Shared/Recruit.Shared.Web/TagHelpers/ConditionTagHelper.cs
I have introduced couple of new tag helpers asp-show and asp-hide to replace asp-condition. These read a lot better on the page and also we can avoid creating negating booleans. I haven't applied it everywhere as it is a big undertaking, a tech debt task is open to address this refactoring.
=> ER-721 Hides incomplete fields message when editing rejected vacancy

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Console.RecruitSeedDataWriter.csproj, src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/BlockedEmployers.json, src/Data/CosmosDb/Console.RecruitSeedDataWriter/SeedScript.ps1, src/Employer/Employer.Web/Attributes/CheckEmployerBlockedAttribute.cs, src/Employer/Employer.Web/Caching/Cache.cs, src/Employer/Employer.Web/Caching/ICache.cs, src/Employer/Employer.Web/Configuration/CacheKeys.cs, src/Employer/Employer.Web/Configuration/IoC.cs, src/Employer/Employer.Web/Configuration/ViewNames.cs, src/Employer/Employer.Web/Controllers/ApplicationReviewController.cs, src/Employer/Employer.Web/Controllers/CreateVacancyOptionsController.cs, src/Employer/Employer.Web/Controllers/DashboardController.cs, src/Employer/Employer.Web/Controllers/ErrorController.cs, src/Employer/Employer.Web/Controllers/LogoutController.cs, src/Employer/Employer.Web/Controllers/VacancyManageController.cs, src/Employer/Employer.Web/Controllers/VacancyPreviewController.cs, src/Employer/Employer.Web/Exceptions/BlockedEmployerException.cs, src/Employer/Employer.Web/Extensions/HttpContextExtensions.cs, src/Employer/Employer.Web/Filters/CheckEmployerBlockedFilter.cs, src/Employer/Employer.Web/Startup.Configure.cs, src/Employer/Employer.Web/Startup.ConfigureServices.cs, src/Employer/Employer.Web/Views/Error/BlockedEmployer.cshtml, src/Shared/Recruit.Vacancies.Client/Application/Configuration/BlockedEmployers.cs, src/Shared/Recruit.Vacancies.Client/Application/Providers/IBlockedEmployersProvider.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/BlockedEmployers/BlockedEmployersProvider.cs, src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs
- Added In-Memory cache and our own `Cache.cs` abstraction wrapper around it
- As this 'blocking' is not part of normal system behaviour and more of a authorisation concern I have implemented as an MVC attribute/filter and have kept it outside of the Recruit Client.
- Added seeding json to populate `configuration` collection
- To add an employer account id just add a string to the array
`{
"_id": "BlockedEmployers",
"employerAccountIds": ["AAAAAA", "BBBBB"]
}`
- The blocked employers list will be cached once a day.  If we need a block to happen quicker than that we'll need to bounce the application.  Keeping it simple for now.
=> ER-663 blocked employers

src/Employer/Employer.Web/Configuration/IoC.cs, src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs, src/Employer/Employer.Web/Controllers/ErrorController.cs, src/Employer/Employer.Web/Controllers/LegalEntityAgreementController.cs, src/Employer/Employer.Web/Controllers/Part1/EmployerController.cs, src/Employer/Employer.Web/Controllers/VacancyPreviewController.cs, src/Employer/Employer.Web/Employer.Web.csproj, src/Employer/Employer.Web/Models/PostEmployerEditModelResponse.cs, src/Employer/Employer.Web/Models/SubmitVacancyResponse.cs, src/Employer/Employer.Web/Orchestrators/LegalEntityAgreementOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/Part1/EmployerOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/VacancyPreviewOrchestrator.cs, src/Employer/Employer.Web/Services/ILegalEntityAgreementService.cs, src/Employer/Employer.Web/Services/LegalEntityAgreementService.cs, src/Employer/Employer.Web/Utility.cs, src/Employer/Employer.Web/ViewModels/LegalEntityAgreement/LegalEntityAgreementHardStopViewModel.cs, src/Employer/Employer.Web/ViewModels/LegalEntityAgreement/LegalEntityAgreementSoftStopViewModel.cs, src/Employer/Employer.Web/Views/LegalEntityAgreement/LegalEntityAgreementHardStop.cshtml, src/Employer/Employer.Web/Views/LegalEntityAgreement/LegalEntityAgreementSoftStop.cshtml, src/Employer/Employer.Web/wwwroot/css/application.css, src/Shared/Recruit.Vacancies.Client/Domain/Entities/Vacancy.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/EditVacancyInfo/LegalEntity.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/EmployerAccount/LegalEntityMapper.cs, src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj
Upgraded package `SFA.DAS.Account.Api.Client` to version 1.3.1331.
Added `LegalEntityAgreementService`. This is injected into orchestrators that need to know if a legal entity has a signed agreement.
- This service first checks the `EditVacancyInfo` projection to see if the `hasLegalEntityAgreement` is set to true. If `true` the journey continues as normal. (This will be the most common scenario)
- If `false` the service checks the Employer Service directly as the agreement could have been signed after the `EditVacancyInfo` projection was last rebuilt
- if the employer has signed an agreement then a command is fired for the jobs to rebuild the `EditVacancyInfo` projection (This will set  `hasLegalEntityAgreement` to true in the projection) and the journey continues as normal.
- if the …
=> ER-766 - Legal entity agreement

src/Employer/Employer.Web/Controllers/Part2/TrainingProviderController.cs, src/Employer/Employer.Web/Orchestrators/Part2/TrainingProviderOrchestrator.cs, src/Employer/Employer.Web/ViewModels/Part2/TrainingProvider/SelectTrainingProviderViewModel.cs, src/Employer/Employer.Web/Views/Part2/TrainingProvider/SelectTrainingProvider.cshtml
This fixes a couple of issues:
In IE Edge the implementation of `type='number'` allows you to enter alphanumerics but prevents the form from being submitted.  We have code to disable submit buttons to prevent multiple form submits so the button gets disabled and never gets re-enabled.
The other issue is you can increment/decrement the number using up/down arrows & mouse scroll wheel. This is not useful behaviour with regard to UKPRNs.
So to fix this issue I'm changing the input from number to text. We have regex as part of server-side validation already to ensure numbers are used
=> ER-811 - Training provider input changed from number to text

src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs, src/Employer/Employer.Web/Controllers/EditVacancyDatesController.cs, src/Employer/Employer.Web/Controllers/ErrorController.cs, src/Employer/Employer.Web/Controllers/VacancyManageController.cs, src/Employer/Employer.Web/Extensions/CookiesExtensions.cs, src/Employer/Employer.Web/Orchestrators/EditVacancyDatesOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs, src/Employer/Employer.Web/ViewModels/ErrorMessages.cs, src/Employer/Employer.Web/Views/EditVacancyDates/EditVacancyDates.cshtml, src/Shared/Recruit.Vacancies.Client/Domain/Entities/Vacancy.cs
No longer clearing the cookies when Cancelling from the Edit Dates page.  Instead I'm ensuring cookies are cleared when we land on the Manage vacancy page.
Added handling of AggregateException in ErrorController. This is thrown from Task.WaitAll.
Refactored the Start/Closing date extending functionality to make the controller more skinny & move logic into orch as per other pages in employer Web.
Simplifying state handling by just throwing an InvalidStateException rather than marshalling redirects should a vacancy be in the wrong state.
=> ER-807 - Closing date extension

src/Employer/Employer.Web/Controllers/ErrorController.cs, src/Employer/Employer.Web/Exceptions/BlockedEmployerException.cs, src/Employer/Employer.Web/Filters/CheckEmployerBlockedFilter.cs
This is very crude and done to address the unhandled exception we are seeing on PROD.
Writing a custom middleware to intercept the exception was troublesome and I am not sure whether we need to throw an exception to intercept.
I also think it may be worth turning the `CheckEmployerBlockedFilter` into an `AuthorizationFilter`
=> ER-831 - Redirect to blocked employer error page from action filter

src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/CustomValidators/VacancyValidators/VacancyFluentValidationExtensions.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs
Webjobs failed to start if the apprenticeship programmes were not populated in the collection.
This was due to the Singleton instance of the vacancy validator making a call to get them on webjob initialisation
Have made it a lazy call in that validator setup.
=> Fix issue with startup of webjob

src/Employer/Employer.Web/Configuration/ConfigurationExtensions.cs
We see 'Correlation Failed' error when the user has spent > 15 mins on logon page before logging in. This is a built in security feature. The timeout value can be configured.
This fix catches this exception and redirects to the root which in effect makes them start from the employer start page again.
=> Redirect to root if auth fails

src/Employer/Employer.Web/Configuration/ApplicationInsightsConfiguration.cs, src/Employer/Employer.Web/Configuration/IoC.cs, src/Employer/Employer.Web/Employer.Web.csproj, src/Employer/Employer.Web/Startup.Configure.cs, src/Employer/Employer.Web/Views/ApplicationReview/ApplicationReview.cshtml, src/Employer/Employer.Web/Views/Part1/Employer/Employer.cshtml, src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml, src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml, src/Employer/Employer.Web/Views/Part2/ApplicationProcess/ApplicationProcess.cshtml, src/Employer/Employer.Web/Views/PartialNames.cs, src/Employer/Employer.Web/Views/Shared/_ApplicationInsightsPartial.cshtml, src/Employer/Employer.Web/Views/Shared/_Layout.cshtml, src/Employer/Employer.Web/Views/Shared/_LayoutWithoutNavigation.cshtml, src/Employer/Employer.Web/Views/_ViewImports.cshtml, src/Shared/Recruit.Shared.Web/Views/Shared/_GoogleTagManagerHeadPartial.cshtml
In readiness for the HTML editor we want to add for ER-822 to use I've tightened our CSP.  Previously we allowed unsafe-inline for script sources which I have now removed and replaced with nonces.
- Upgraded NWebSec and added NWebSec MVC & HtmlHelpers
- Added a partial for ApplicationInsights to replace the helper function so we can add a nonce to the script tag
=> ER-858 - Removing script unsafe-inline and using nonce instead

src/Employer/Employer.Web/appsettings.json
Filtering out the warning messages like 
`
'.AspNetCore.Correlation.oidc.1v9oZ16D5qHsoLyu7xYWAviHVoK1l1lZIzCWSwZTymE' cookie not found
`
from our logs.
It does mean all logs that are not errors from that oidc handler wont be logged.
=> Filter out warning logs for the oidc handler

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/BannedPhrases.json
Not sure why some of the words in the list starts with uppercase letter and some don't, do we need to make it consistent by having all the words in lowercase?
=> ER-835 Adds School to banned phrases

src/Data/Recruit.ChangeScripts/020-qualification-equivalent.js, src/Data/Recruit.ChangeScripts/030-qualification-equivalent-reviews.js
These cosmos scripts were failing when being deployed to PRE as the document returned by the aggregate was too big.
=> ER-821 - Fixed issue with aggregate being too big on large datasets

src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs
Recreating the published vacancies was failing during the bulk insertion of vacancies to the querystore.  This is due to the RU limit being reached and throwing `Error executing Mongo Command for method RecreateAsync Reason: A bulk write operation resulted in one or more errors. Message: {"Errors":["Request rate is large"]}`.
The retry would then execute then we would get duplicate key errors `Error executing Mongo Command for method RecreateAsync Reason: A bulk write operation resulted in one or more errors.
E11000 duplicate key error collection: recruit.queryStore Failed _id or unique key constraint. Retrying in 2 secs...attempt: 2`
So I've changed the inserting of entities to be done one at a time.
=> ER-850 - Fixing recreation of published vacancies

src/.vscode/launch.json, src/Employer/Employer.Web/Configuration/ConfigurationExtensions.cs, src/Employer/Employer.Web/Employer.Web.csproj, src/Employer/Employer.Web/Program.cs, src/Employer/Employer.Web/Startup.ConfigureServices.cs, src/Employer/UnitTests/UnitTests.csproj, src/Provider/Provider.Web/Configuration/ConfigurationExtensions.cs, src/Provider/Provider.Web/Program.cs, src/Provider/Provider.Web/Provider.Web.csproj, src/Provider/Provider.Web/Startup.ConfigureServices.cs, src/QA/QA.Web/Configuration/ServiceCollectionExtensions.cs, src/QA/QA.Web/Program.cs, src/QA/QA.Web/QA.Web.csproj, src/QA/QA.Web/Startup.ConfigureServices.cs, src/QA/UnitTests/UnitTests.csproj
The issues that were being logged during deployment such as:
- Startup assembly Microsoft.AspNetCore.AzureAppServices.HostingStartup failed to execute. See the inner exception for more details.
- Startup assembly StartupBootstrapper failed to execute. See the inner exception for more details.
- Could not load file or assembly 'D:\home\site\wwwroot\Recruit.Shared.Web.Views.dll'. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020) 
- Other process locks like above
No longer occur after deploying this branch on AT and test multiple times.
We will need to revisit the aspnet core 2.2 upgrade again in the future. The same with the usage of DataProtection through Redis.
We have been seeing some issues such as `An attempt was made …
=> Downgrade aspnetcore2.2

src/Shared/Recruit.Vacancies.Client/Application/Rules/BaseRules/BaseBannedPhraseChecksRule.cs, src/Shared/Recruit.Vacancies.Client/Application/Rules/Extensions/StringExtensions.cs, src/Shared/UnitTests/Vacancies.Client/Application/Rules/VacancyRules/TestVacancyBuilder.cs, src/Shared/UnitTests/Vacancies.Client/Application/Rules/VacancyRules/VacancyBannedPhraseChecksRuleTest.cs
The FormatForParsing was replacing only black listed special characters, I inverted it to white listing alpha-numerics so everything else gets replaced.
=> RA-835 Fixes banned phrases not picked as prefixed by special chars

src/Employer/Employer.Web/Orchestrators/Part1/TitleOrchestrator.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs
Now that Provider is using it's own CreateVacancy method, it is safe to assume the UserType here as Employer as this method is only invoked from Employer recruit.  
PS: I don't like my comment here but the 💩 VacancyClient implementation has forced me to do this.
=> Defaults user type in employer create vacancy method

src/Employer/Employer.Web/Orchestrators/Part1/TitleOrchestrator.cs, src/Provider/Provider.Web/Controllers/Part1/EmployerController.cs, src/Provider/Provider.Web/Controllers/Part1/TitleController.cs, src/Provider/Provider.Web/Extensions/ClaimsPrincipalExtensions.cs, src/Provider/Provider.Web/Orchestrators/Part1/EmployerOrchestrator.cs, src/Provider/Provider.Web/Orchestrators/Part1/TitleOrchestrator.cs, src/Provider/Provider.Web/ViewModels/Part1/Title/TitleEditModel.cs, src/Provider/Provider.Web/ViewModels/Part1/Title/TitleViewModel.cs, src/Provider/Provider.Web/ViewModels/ValidationMessages.cs, src/Provider/Provider.Web/Views/Dashboard/Dashboard.cshtml, src/Provider/Provider.Web/Views/Part1/Employer/Employer.cshtml, src/Provider/Provider.Web/Views/Part1/Title/Title.cshtml, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/CreateProviderOwnedVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/CreateProviderOwnedVacancyCommand.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/ProviderVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStoreClient.cs
- Manually adding validation on Employers page as the vacancy hasn't been created yet and it was causing some pain to do that. 
- Reading the ukprn from the User object rather than from route path. 
- I have commented unused copied code, this can be uncommented/changed/removed in the follow up stories. 
- TitleViewModel does not derive from TitleEditModel
=> ER-933 provider part1 Title

src/Provider/Provider.Web/Configuration/IoC.cs, src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs, src/Provider/Provider.Web/Controllers/Part1/LocationController.cs, src/Provider/Provider.Web/Controllers/Part1/ShortDescriptionController.cs, src/Provider/Provider.Web/Orchestrators/Part1/LocationOrchestrator.cs, src/Provider/Provider.Web/Utility.cs, src/Provider/Provider.Web/ViewModels/Part1/Location/LegalEntityViewModel.cs, src/Provider/Provider.Web/ViewModels/Part1/Location/LocationEditModel.cs, src/Provider/Provider.Web/ViewModels/Part1/Location/LocationViewModel.cs, src/Provider/Provider.Web/Views/Part1/Location/Location.cshtml, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/ProviderVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/IQueryStoreReader.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/Projections/EditVacancyInfo/EmployerInfo.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStoreClient.cs
This one is identical to Employer's but not exact match. 
- The route used is `location` as `employer` is used for the first step. 
- No checks for soft/hard stop on legal entities selection as this is assumed. 
- Employer name will **not** be updated with legal entity name
- Some styling is missing, waiting on Richard to send me prototype
=> ER-875 Implements provider step 1 location

src/Employer/Employer.Web/Configuration/ExternalLinksConfiguration.cs, src/Employer/Employer.Web/Configuration/ManageApprenticeshipsLinkHelper.cs, src/Employer/Employer.Web/Startup.Configure.cs, src/Employer/Employer.Web/appsettings.json, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json
https://skillsfundingagency.atlassian.net/browse/ER-987
Added new config value specifically for the commitments site to resolve the problem with the 'Apprentices' links only working in PRE/PROD
=> Fix apprentices link

src/QA/QA.Web/Views/Review/Review.cshtml
It makes sense to only mark the Provider for reviewing if the vacancy is an Employer vacancy.
=> ER-887 - Only show Provider review checkbox for employer vacancies

src/Employer/Employer.Web/Configuration/Routing/ManageApprenticeshipsRoutes.cs, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json, src/Provider/Provider.Web/Configuration/ExternalLinksConfiguration.cs, src/Provider/Provider.Web/Configuration/IoC.cs, src/Provider/Provider.Web/Configuration/ProviderApprenticeshipsLinkHelper.cs, src/Provider/Provider.Web/Configuration/Routing/ProviderApprenticeshipsRoutes.cs, src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs, src/Provider/Provider.Web/Configuration/Routing/RoutePaths.cs, src/Provider/Provider.Web/Controllers/ExternalLinksController.cs, src/Provider/Provider.Web/Controllers/LogoutController.cs, src/Provider/Provider.Web/Startup.Configure.cs, src/Provider/Provider.Web/Views/Shared/_Layout.cshtml, src/Provider/Provider.Web/appsettings.json, src/Provider/Provider.Web/wwwroot/css/application.css, src/Provider/Provider.Web/wwwroot/lib/esfa-provider-menu/style.css, src/Shared/Recruit.Vacancies.Client/Infrastructure/Mongo/MongoDbCollectionBase.cs
This is basic.
Going forward we will be using a shared partial across DAS for the employer and Provider menu's these should also take not of the whitelisting and env differences for showing particular menu items.
I have copied in the way that the footer is on the PAS website on test, including a survey link to AccessMyLevy, we can change this as we get a survey for provider recruit or drop it all together.
I have left out the reservations link which might appear on the other env's because it is not showing up on TEST yet. We will have to revisit this when going through the env's to make sure the menu items are the same across other das services.
=> ER-972 provider navigation menu

src/Data/Recruit.ChangeScripts/010-vacancies_Insert_EmployerNameOption.js
In batches of 500, loop through all non-deleted vacancies where `employerNameOption` property does not exist.
for each matched document set `employerNameOption` to "RegisteredName"
if `employerName` has been specified on the vacancy then also set `legalEntityName` to the vacancy's `employerName`
=> ER-1147 - EmployerNameOption backfill change script.

src/Provider/Provider.Web/Configuration/CookieNames.cs
Renamed a couple of provider cookies so all provider cookies now start with `prov-`. Documentation has also been adjusted
=> ER-1110 - renamed provider cookies

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/RecruitWebJobsSystem.json
This is to turn off the job. We will enable it selectively when testing along with FAA/Vacancy API and keep it turned on when the full integration is in place.
=> Turn off VacancyAnalyticsSummary gen job

src/Provider/Provider.Web/Configuration/ConfigurationExtensions.cs, src/Provider/Provider.Web/Middleware/ProviderAccountHandler.cs, src/Provider/Provider.Web/Views/Error/AccessDenied.cshtml
Added an extra claim check to Provider.Web.  Every user must have the claim:
`http://schemas.xmlsoap.org/ws/2005/05/identity/claims/service` with a value of `DAA`
=> ER-1192 - Provider require DAA service claim

src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/PatchVacancyTrainingProviderCommandHandler.cs, src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/CloneVacancyCommandHandlerTests.cs, src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/PatchVacancyTrainingProviderCommandHandlerTests.cs, src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/SubmitVacancyCommandHandlerTests.cs, src/Shared/UnitTests/Vacancies.Client/Infrastructure/Extensions/VacancyExtensionsTests.cs
Note this is a stop gap solution to support smoke testing without causing a flood of error logs.
The domain event handler picks up on DraftVacancyUpdatedEvent and kicks off the PatchTrainingProvider command handler and processes when the vacancy is Provider Owned and the name and address hasn't been populated.
=> ER-1259 - Patch ESFA training provider details instead of calling Providers API for ESFA owned Provider vacancies

src/Employer/Employer.Web/nlog.config, src/Provider/Provider.Web/Controllers/ErrorController.cs, src/Provider/Provider.Web/nlog.config
Invalid state exception is raised when an disallowed action is requested. Since this is handled, it shouldn't be logged as error as there is not much we can do about it. Instead, we need to raise this as a warning and keep an eye on the number of occurrences. If too many instance of these warnings are logged we may have to investigate the user actions. 
Also I have added missing user info to provider's and employer's log.
=> Changes log level for invalid state exception

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Console.RecruitSeedDataWriter.csproj, src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/BlockedEmployers.json, src/Data/CosmosDb/Console.RecruitSeedDataWriter/SeedScript.ps1, src/Employer/Employer.Web/Configuration/ConfigurationExtensions.cs, src/Employer/Employer.Web/Configuration/FeatureNames.cs, src/Employer/Employer.Web/Startup.ConfigureServices.cs, src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml, src/Employer/Employer.Web/appsettings.json, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json, src/Shared/Recruit.Shared.Web/TagHelpers/EsfaFeatureTagHelper.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/ApprenticeshipProgrammes/ApprenticeshipProgrammesUpdateService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/ReferenceData/BankHolidays/BankHolidayUpdateService.cs, src/Shared/UnitTests/Vacancies.Client/Infrastructure/ReferenceData/ApprenticeshipProgrammes/ApprenticeshipProgrammesUpdaterServiceTests.cs
Moved feature toggle functionality from Shared.Web to Client so we can use the toggle from the jobs
- Added `EnableLevy` feature toggle
- Toggle turns off the adding of the `LevyDeclarationCheckFilter` in Employer.Web
- Toggle is used in the `NonLevyAccountBlockerJob`. When `EnableLevy` is false the BlockedEmployers list is set to be empty.
=> ER-1178 - Toggle levy functionality

src/Employer/Employer.Web/Configuration/ExternalLinksConfiguration.cs, src/Employer/Employer.Web/ViewModels/DashboardViewModel.cs, src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml, src/Employer/Employer.Web/Views/Dashboard/_NoVacanciesContent.cshtml, src/Employer/Employer.Web/appsettings.json, src/Employer/UnitTests/Employer.Web/Orchestrators/Dashboard/GetDashboardViewModelAsyncTests.cs
We now display quite a lot of content on the landing page when an employer has no vacancies. So I've moved this content into a partial
We now want to display the same content on DEMO and PROD so I have removed the Employer Levy feature toggle (That was short lived!)
We now display links to FAT for searching for training and providers.  I've added these url to appsettings.json
=> ER-1294 - Employer landing page content

src/Employer/Employer.Web/Controllers/Part1/TrainingProviderController.cs, src/Employer/Employer.Web/Models/PostSelectTrainingProviderResult.cs, src/Employer/Employer.Web/Orchestrators/Part1/TrainingProviderOrchestrator.cs, src/Employer/UnitTests/Employer.Web/Orchestrators/Part1/TrainingProviderOrchestratorTests.cs, src/Provider/Provider.Web/Controllers/ErrorController.cs, src/Provider/Provider.Web/Middleware/ProviderAccountHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/PatchVacancyTrainingProviderCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Configuration/EsfaTestTrainingProvider.cs, src/Shared/Recruit.Vacancies.Client/Application/Providers/ITrainingProviderSummaryProvider.cs, src/Shared/Recruit.Vacancies.Client/Domain/Entities/TrainingProviderSummary.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IRecruitVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProvider/ITrainingProviderService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProvider/TrainingProviderService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProvider/TrainingProviderSuggestion.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProviderSummaryProvider/TrainingProviderSummaryProvider.cs, src/Shared/Recruit.Vacancies.Client/Ioc/ServiceCollectionExtensions.cs, src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/PatchVacancyTrainingProviderCommandHandlerTests.cs
Whenever a user accesses Provider.Web we need to check that the Provider is listed on RoATP.
This check is done in `ProviderAccountHandler` which is called on every page request. To prevent this triggering a call to the FAT API on every request I'm using the existing SetupProvider cookie to determine if this check has been done already in the session.
Assumption: All we need to do to check if a provider is in RoATP is to try and get the provider from from the FAT Api and if the provider does not exist then this means they are not in RoATP.  Is this correct?  This is how PAS does it.
=> ER-919 - Provider RoATP check

src/Provider/Provider.Web/Orchestrators/Reports/ProviderApplicationsReportOrchestrator.cs, src/Provider/Provider.Web/Orchestrators/Reports/ReportDashboardOrchestrator.cs, src/Provider/UnitTests/Provider.Web/Orchestrators/Reports/ProviderApplicationsReportOrchestratorTests.cs, src/QA/QA.Web/ViewModels/ReviewHistoryViewModel.cs, src/QA/QA.Web/ViewModels/ReviewViewModel.cs, src/QA/QA.Web/Views/Dashboard/Index.cshtml, src/Shared/Recruit.Shared.Web/Extensions/StringExtensions.cs, src/Shared/Recruit.Vacancies.Client/Domain/Extensions/DateTimeExtensions.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Reports/ReportService.cs
We have various places in the system where we display the time.  As we have been using `.ToLocalTime()` this works fine when developing locally as our machines are set to handle daylight savings.  However the Azure boxes are set to use UTC so are an hour out in the summer.
There are various ways of fixing this.  We could in config set the Azure services to run in GMT Standard Time and handle daylight savings, however this feels a bit of a sledge hammer to crack a nut and it makes sense to me that cloud services are not time zone aware.
As this is an England only service I don't think we need to be too clever regarding localisation of time 
so instead I've created an extension method `.ToUkTime()` which will explicitly set the time to `GMT Standard Time` (which handles daylight saving). …
=> ER-1187 - UTC to GMT Standard conversion

src/Employer/Employer.Web/Controllers/Part1/EmployerController.cs, src/Provider/Provider.Web/Controllers/Part1/LegalEntityController.cs
Bug where returning to the legal entity selection page from part 2 and paging through search results and then clicking cancel would take the user back to dashboard instead of part 2 preview. Clicking continue would take the user through the legal entity sub-journey and then through the rest of part 1 instead of through to part 2 preview.
=> ER-1343 Persisting wizard from legal entities selection results pages

src/Data/Recruit.ChangeScripts/040-vacancies_clearClosedByUserFieldOnSystemClosedCloneVacancies.js
I have done a check for running this script against PROD and around 67 vacancies will be treated.
The script outputs the vacancies that will and will not be affected as well as the original value that is being cleared.
This script will needs its file renaming to be ordered correctly again when it makes it into the target master and after #676 is merged.
=> ER-1021 changeScript for unsetting 'closedByUser' on closed closed clone vacancies

src/Shared/Recruit.Vacancies.Client/Domain/Extensions/DateTimeExtensions.cs, src/Shared/Recruit.Vacancies.Client/Recruit.Vacancies.Client.csproj
This is to fix an issue that I have running the code on my machine along with unit tests causing the following error
```
System.TimeZoneNotFoundException : The time zone ID 'GMT Standard Time' was not found on the local computer.
---- System.IO.FileNotFoundException : Could not find file '/usr/share/zoneinfo/GMT Standard Time'.
https://stackoverflow.com/questions/47848111/how-should-i-fetch-timezoneinfo-in-a-platform-agnostic-way
```
Issue is described further:
- https://stackoverflow.com/questions/47848111/how-should-i-fetch-timezoneinfo-in-a-platform-agnostic-way
- https://github.com/dotnet/corefx/issues/11897
=> ER-1419 - Fixing GetTimeZone call so it works on a mac

src/Shared/Recruit.Vacancies.Client/Domain/Entities/TransferInfo.cs, src/Shared/Recruit.Vacancies.Client/Domain/Entities/TransferReason.cs
We need to know the reason why a vacancy was transferred.  The 2 possibilities are:
1. The Employer revoked a provider's permission
2. The QA has blocked a provider
For closed vacancies we could use the `ClosureReason` to work this out however for Drafts that just get transferred and not closed we are missing this data to make this decision.
=> ER-1414 - Added TransferReason

src/Employer/Employer.Web/Controllers/Part1/TrainingProviderController.cs, src/Employer/Employer.Web/Models/PostSelectTrainingProviderResult.cs, src/Employer/Employer.Web/Orchestrators/Part1/TrainingProviderOrchestrator.cs, src/Employer/UnitTests/Employer.Web/Orchestrators/Part1/TrainingProviderOrchestratorTests.cs, src/Shared/Recruit.Vacancies.Client/Application/Providers/ITrainingProviderSummaryProvider.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/ErrorCodes.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/CustomValidators/VacancyValidators/VacancyFluentValidationExtensions.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/TrainingProviderValidator.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProviderSummaryProvider/TrainingProviderSummaryProvider.cs, src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/SingleField/TrainingProviderUkprnValidationTests.cs, src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/VacancyValidationTestsBase.cs
- Moved the checking of the provider is in RoATP and is also not Blocked out of the Training Provider orchestrator and into the Validations.  This allows the same logic to be run as part of the vacancy submit process too.
- Changed the list of Apprenticeship Programmes in the Validator from a Lazy list to using the cached lookup.  As Fluent validation is Singleton then I think this list wouldn't get updated unless the application recycled so now its using the cached provider it will be in sync.
- Added an ErrorCodes class to list some error codes that I needed the orchestrator to be aware of.  Maybe this class could become the beginning of the definitive list of error codes?
- I've changed some of the validations from `.Custom` to `.CustomAsync`. This allows us to write the validation …
=> ER-1378 - blocked training provider validation. Employer.Web

src/Employer/Employer.Web/Views/Part1/Training/Training.cshtml, src/Provider/Provider.Web/Views/Part1/Training/Training.cshtml
If someone goes back to change the training and searches for 'fffffff' then the page would continue to the confirm page using their existing training.
This now defaults the selected option to the default "" if they try and submit an unmatched entry. This will then kick in the validation error.
I'm not liking Accessible Autocomplete. Its lacking somewhat.
=> ER-1337 ER-1344 - Handling unmatched training searches

src/Employer/Employer.Web/Views/Dashboard/Dashboard.cshtml, src/QA/QA.Web/Views/Dashboard/Index.cshtml
Hiding the "block provider" and "withdraw vacancy" from QA web and "transferred" filter from employer web to allow public beta release to go ahead.
=> ER-1457 hide block provider links

src/QA/QA.Web/Controllers/WithdrawVacancyController.cs, src/QA/QA.Web/Models/WithdrawVacancy/PostFindVacancyEditModelResult.cs, src/QA/QA.Web/Orchestrators/WithdrawVacancyOrchestrator.cs, src/QA/QA.Web/Views/WithdrawVacancy/Confirm.cshtml, src/QA/UnitTests/Qa.Web/Orchestrators/WithdrawVacancyOrchestrator/PostFindVacancyEditModelAsyncTests.cs
ER-1106 Show correct error message when closing a vacancy that isn't live
ER-1106 Preserve user input when cancelling vacancy closure
ER-1106 Remove Cancel option from Confirmation screen
=> ER-1106 Withdrawn live vacancy +semver: patch

src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/ProviderBlockedOnLegalEntityDomainEventHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Vacancy/ProviderBlockedOnVacancyDomainEventHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/CloseVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ResetSubmittedVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/TransferProviderVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/CloseVacancyCommand.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/ResetSubmittedVacancyCommand.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/TransferProviderVacancyCommand.cs, src/Shared/Recruit.Vacancies.Client/Application/Services/IVacancyService.cs, src/Shared/Recruit.Vacancies.Client/Application/Services/VacancyReviewTransferService.cs, src/Shared/Recruit.Vacancies.Client/Application/Services/VacancyService.cs, src/Shared/Recruit.Vacancies.Client/Domain/Events/VacancyReviewWithdrawnEvent.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/QaVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateEmployerDashboardOnChange.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateProviderDashboardOnChangeEventHandler.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/EventHandlers/UpdateQaDashboardOnReview.cs
Broken down the update of vacancy in three commands
- Apply transfer
- Reset submitted vacancy to draft
- Close live vacancy
I have refactored close vacancy command to update the vacancy and raise the event. This command can potentially be reused from all the cases where we need to close vacancies. Also this is the first step to get rid of VacancyService which is very ambiguous by name.
=> ER-1445 Refactored vacancy treatment on provider blocked

src/.vscode/launch.json, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.json, src/Employer/Esfa.Recruit.Azure.Resources/azuredeploy.parameters.json, src/Jobs/Recruit.Vacancies.Jobs/ExternalSystemEventHandlers/UpdatedPermissionsExternalSystemEventsHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/Program.cs, src/Jobs/Recruit.Vacancies.Jobs/Recruit.Vacancies.Jobs.csproj, src/Jobs/Recruit.Vacancies.Jobs/ServiceCollectionExtensions.cs, src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/SpikeQueueTrigger.cs, src/Jobs/Recruit.Vacancies.Jobs/appSettings.json, src/Shared/UnitTests/Jobs/ExternalSystemEventHandlers/UpdatedPermissionsExternalSystemEventHandlerTests.cs, src/Shared/UnitTests/UnitTests.csproj
I have run a simple test on TEST 2 where I have revoked a permission and a vacancy has been transferred.
- Upgraded webjobs to 2.2 to be able to use Das configuration (This seems to work without issues)
- If you have Encodings config in your webjobs secrets, please remove as we will now be using the DAS shared Encoding
- You will need to run the das-employer-config-updater tool with the environment set to `Development` - Mark has done this recently for provider relationships so he can help
- I will remove the Encodings config from the ARM template and Release definition after this piece goes out.
- If using Visual Studio, you may have to adjust your launchSettings.json for the webjobs project to use the environment variables as I have declared in the launch.json file in this PR
=> Encoding service to use shared config

src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs, src/Employer/Employer.Web/ViewModels/VacancyManage/ManageVacancyViewModel.cs, src/Employer/Employer.Web/Views/VacancyManage/ManageVacancy.cshtml, src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Vacancy/ProviderBlockedOnVacancyDomainEventHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApproveVacancyReviewCommandHandler.cs, src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/ApproveVacancyReviewCommandHandlerTests.cs
Added some content to the Manage vacancy screen for closed vacancies.
Also added fix so:
> 1. if the vacancy to be closed is one where an employer has given permission (so the provider created it) then it is transferred to the employer. closure reason = transferred by QA
> 2. if the vacancy to be closed is NOT one where an employer has given permission (they created it themselves and chose the provider) then it is just closed. closure reason = blocked by QA
=> ER-1406 - Added content for employer vacancies closed due to blocked provider

src/Employer/Employer.Web/Controllers/VacancyPreviewController.cs, src/Employer/Employer.Web/Orchestrators/Part1/WageOrchestrator.cs, src/Employer/Employer.Web/Orchestrators/VacancyPreviewOrchestrator.cs, src/Employer/Employer.Web/ViewModels/Part1/Wage/WageViewModel.cs, src/Employer/Employer.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs, src/Employer/Employer.Web/Views/Part1/Wage/Wage.cshtml, src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml, src/Provider/Provider.Web/Orchestrators/Part1/WageOrchestrator.cs, src/Provider/Provider.Web/ViewModels/Part1/Wage/WageViewModel.cs, src/Provider/Provider.Web/Views/Part1/Wage/Wage.cshtml, src/Shared/Recruit.Shared.Web/Extensions/StringExtensions.cs, src/Shared/Recruit.Shared.Web/Extensions/WageExtensions.cs, src/Shared/Recruit.Shared.Web/Orchestrators/EntityValidatingOrchestrator.cs, src/Shared/Recruit.Shared.Web/ViewModels/ErrorListItemViewModel.cs, src/Shared/Recruit.Shared.Web/Views/RecruitPartialNames.cs, src/Shared/Recruit.Shared.Web/Views/Shared/_ErrorListItemPartial.cshtml, src/Shared/Recruit.Shared.Web/Views/Shared/_ValidationSummaryPartial.cshtml, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/CustomValidators/VacancyValidators/VacancyFluentValidationExtensions.cs, src/Shared/Recruit.Vacancies.Client/Domain/Extensions/StringExtensions.cs, src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/CrossField/FixedWageAmountValidation.cs
Added the concept of `Soft Validations`  these get run on the GET of the vacancy preview.
Refactored `_ValidationSummaryPartial.cshtml ` to pull out the generation of the error list into a separate partial `_ErrorListItemPartial.cshtml` so we can reuse when building the soft validations summary.
Refactored `WageOrchestrator.GetMinimumWageYearlyText` so directly uses `WagePresenter` without having to create a temporary `Wage`object.
=> ER-1489 - wage and pay validations. Employer.Web

src/Employer/Employer.Web/Controllers/VacancyPreviewController.cs, src/Employer/Employer.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs, src/Employer/Employer.Web/Views/VacancyPreview/VacancyPreview.cshtml, src/Provider/Provider.Web/Controllers/VacancyPreviewController.cs, src/Provider/Provider.Web/Orchestrators/VacancyPreviewOrchestrator.cs, src/Provider/Provider.Web/ViewModels/VacancyPreview/VacancyPreviewViewModel.cs, src/Provider/Provider.Web/Views/VacancyPreview/VacancyPreview.cshtml
Added the concept of 'soft validation errors' to Provider.Web. These get displayed on the GET of the vacancy preview.
I have also refactored the calculation of the Section Count (In Employer.Web and Provider.Web) to reduce the complexity of the vacancy preview controllers.
=> ER-1490 wages and pay validations. Provider.Web

src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ResetSubmittedVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Services/VacancyReviewTransferService.cs, src/Shared/Recruit.Vacancies.Client/Domain/Entities/ManualQaOutcome.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyReviewRepository.cs, src/Shared/UnitTests/Vacancies.Client/Application/Services/VacancyReviewTransferServiceTests.cs
Given changing the enum value I will be running the following on TEST as part of deploying this:
`db.vacancyReviews.updateMany({"manualOutcome":"Withdrawn"}, { "$set": {"manualOutcome":"Blocked"}})`
=> ER-1367 Removing Withdrawn as a possible ManualOutcome of vacancy in place of Blocked

src/Communication/Communication.Core/CommunicationProcessor.cs, src/Communication/Communication.Types/CommunicationRequest.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandlerTests/GivenEmployerOwnedLiveVacancies.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandlerTests/GivenEmployersWithPermissionsOnly.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandlerTests/GivenProviderOwnedVacancies.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandlerTests/HandleAsyncTests.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandlerTests/ProviderBlockedDomainEventHandlerTestBase.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/DomainEvents/Handlers/VacancyReferredDomainEventHandlerTests.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/ExternalSystemEventHandlers/UpdatedPermissionsExternalSystemEventHandlerTests.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/Jobs/TransferVacanciesFromProviderJobTests.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/Jobs/TransferVacancyToLegalEntityJobTests.cs, src/Jobs/Recruit.Vacancies.Jobs.Tests/Recruit.Vacancies.Jobs.Tests.csproj, src/Jobs/Recruit.Vacancies.Jobs/DomainEvents/Handlers/Provider/ProviderBlockedDomainEventHandler.cs, src/Jobs/Recruit.Vacancies.Jobs/ServiceCollectionExtensions.cs, src/QA/QA.Web/Views/BlockedOrganisations/ConsentForProviderBlocking.cshtml, src/QA/QA.Web/Views/BlockedOrganisations/FindTrainingProvider.cshtml, src/Shared/Recruit.Vacancies.Client/Application/Communications/CommunicationConstants.cs, src/Shared/Recruit.Vacancies.Client/Application/Communications/EntityDataItemProviderPlugins/EmployerDataEntityPlugin.cs, src/Shared/Recruit.Vacancies.Client/Application/Communications/ParticipantResolverPlugins/EmployerParticipantsResolverPlugin.cs, src/Shared/Recruit.Vacancies.Client/Application/Communications/ParticipantResolverPlugins/VacancyParticipantsResolverPlugin.cs, src/Shared/Recruit.Vacancies.Client/Application/Communications/TemplateIdProviderPlugin.cs, src/Shared/Recruit.Vacancies.Client/Application/Communications/UserPreferencesProviderPlugin.cs, src/Shared/Recruit.Vacancies.Client/Domain/Models/ProviderVacancySummary.cs, src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IUserRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbUserRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs, src/Shared/UnitTests/Vacancies.Client/Application/Communications/ParticipantResolverPluginTests.cs, src/Shared/UnitTests/Vacancies.Client/Application/Communications/TemplateIdProviderPluginTests.cs
Introduced data items to CommunicationRequest to allow populate certain calculated values (which cannot be derived later by Entity Data Item Providers) when the request is being created.
Also introduced couple of participant providers, one for employer and one for provider. These will fetch all the users for respective organisation. 
Three different templates were required for employer notification, I have created a method for each type of communication request and added unit tests.
=> ER-1384 provider blocked employer notification

src/QA/QA.Web/Views/BlockedOrganisations/ConfirmTrainingProviderBlocking.cshtml
It now takes user back to the blocked organisation list page.
=> ER-1492 Reinstated the cancel button on confirmation screen

src/Shared/Recruit.Vacancies.Client/Application/Communications/UserPreferencesProviderPlugin.cs, src/Shared/UnitTests/Vacancies.Client/Application/Communications/UserPreferencesProviderPluginTests.cs
In the user preference provider, there was a check if the user preference is not set then return "None" preferences. However in case of certain request types (high severity) we have to bypass user preferences, so even if they are not set, we still have to send the notification emails. 
I have updated the tests accordingly.
=> ER-1506 Fixed provider and employer notifications +semver: patch

src/Provider/Provider.Web/Controllers/Part1/DatesController.cs, src/Provider/Provider.Web/Orchestrators/Part1/DatesOrchestrator.cs, src/Provider/Provider.Web/Orchestrators/VacancyPreviewOrchestrator.cs, src/Provider/Provider.Web/ViewModels/Part1/Dates/DatesViewModel.cs, src/Provider/Provider.Web/Views/Part1/Dates/Dates.cshtml, src/Shared/Recruit.Vacancies.Client/Application/Validation/ErrorCodes.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/CustomValidators/VacancyValidators/VacancyFluentValidationExtensions.cs, src/Shared/Recruit.Vacancies.Client/Application/Validation/Fluent/FluentVacancyValidator.cs, src/Shared/UnitTests/Vacancies.Client/Application/VacancyValidation/CrossField/TrainingExpiryDateValidation.cs
Added extra validation to the Dates page to handle expiring training programmes.  Also added this check to soft validations on vacancy preview.
There is also different content we show depending on whether the training has an expiry date or whether there is an error is displayed due to the training expiry date.
=> ER-1345 - Dates validation. Provider.Web

src/Employer/Employer.Web/Configuration/Routing/RouteNames.cs, src/Employer/Employer.Web/Controllers/Part2/QualificationsController.cs, src/Employer/Employer.Web/Orchestrators/Part2/QualificationsOrchestrator.cs, src/Employer/Employer.Web/ViewModels/Part2/Qualifications/QualificationViewModel.cs, src/Employer/Employer.Web/Views/Part2/Qualifications/Qualification.cshtml, src/Employer/Employer.Web/Views/Part2/Qualifications/Qualifications.cshtml, src/Provider/Provider.Web/Configuration/Routing/RouteNames.cs, src/Provider/Provider.Web/Controllers/Part2/QualificationsController.cs, src/Provider/Provider.Web/Orchestrators/Part2/QualificationsOrchestrator.cs, src/Provider/Provider.Web/ViewModels/Part2/Qualifications/QualificationViewModel.cs, src/Provider/Provider.Web/Views/Part2/Qualifications/Qualification.cshtml, src/Provider/Provider.Web/Views/Part2/Qualifications/Qualifications.cshtml
Renamed `AddQualfication` to `Qualification`. These views/viewmodels/editmodels now create New or Update existing qualifications depending on whether `EditIndex` is specified or not.
=> ER-1429 - Edit Qualifications

src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/VacancySummariesProvider/VacancySummaryAggQueryBuilder.cs
We're now ignoring withdrawn vacancies when calculating the count for New, Successful and Unsuccessful applications.
The bigger change is I've simplified `VacancySummaryAggQueryBuilder` so it just loads the entire aggregate pipeline from a string rather than composing it using a series of BsonDocuments and BsonArrays.  This makes it much easier (for me) to debug as you don't need to interpret it and can just cut-n-paste into RoboMongo.  Hope this refactor isn't too contentious. I took the same approach with the Provider reports.
=> ER-1427 - Ignoring withdrawn applications on dashboard count

src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/VacancySummariesProvider/VacancySummaryAggQueryBuilder.cs
**$match** clause added was filtering out vacancies which had only withdrawn applications. Hence tweaked the status by re-projecting so to not include withdrawn application in the count.
=> ER-1427 Fixed mongo query that generates dashboard +semver: patch

src/.vscode/tasks.json, src/Employer/Employer.Web/Orchestrators/VacancyPreviewOrchestrator.cs, src/Employer/Employer.Web/Utility.cs, src/Provider/Provider.Web/Orchestrators/VacancyPreviewOrchestrator.cs, src/Provider/Provider.Web/Utility.cs, src/Provider/UnitTests/Provider.Web/Orchestrators/CloneVacancyOrchestratorTest/CloneVacancyOrchestratorTestBase.cs, src/Provider/UnitTests/Provider.Web/Orchestrators/CloneVacancyOrchestratorTest/GetCloneableAuthorisedVacancyAsyncTests.cs, src/Provider/UnitTests/Provider.Web/Orchestrators/Part1/LegalEntityOrchestratorTests.cs, src/Provider/UnitTests/Provider.Web/Orchestrators/Part2/SkillOrchestratorTests.cs, src/Provider/UnitTests/Provider.Web/Orchestrators/VacancyPreviewOrchestratorTests.cs, src/Provider/UnitTests/Provider.Web/UtilityTests/GetAuthorisedApplicationReviewAsyncTests.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/SubmitVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Commands/SubmitVacancyCommand.cs, src/Shared/Recruit.Vacancies.Client/Application/Exceptions/ExceptionMessages.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IEmployerVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/IProviderVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/ProviderVacancyClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Client/VacancyClient.cs, src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/SubmitVacancyCommandHandlerTests.cs
I have added check on ownership in the authorization, this should prevent provider from accessing vacancies that have been transferred. 
A related edge case is where a provider submits the vacancy and at the same time the employer revokes the permissions, the vacancy manages to pass through validation and gets submitted. 
To stop this, I have changed command to include the requesting owner and comparing that in the handler with what is on the vacancy. The command will fail in case the owner has changed.
=> ER-1446 Added check on vacancy owner in authorization

src/Data/CosmosDb/Console.RecruitSeedDataWriter/Data/RecruitWebJobsSystem.json, src/Jobs/Recruit.Vacancies.Jobs.UnitTests/Triggers/QueueTriggers/DeleteStaleQueryStoreDocumentsQueueTriggerTests.cs, src/Jobs/Recruit.Vacancies.Jobs.UnitTests/Triggers/QueueTriggers/DeleteStaleVacanciesQueueTriggerTests.cs, src/Jobs/Recruit.Vacancies.Jobs/Configuration/RecruitWebJobsSystemConfiguration.cs, src/Jobs/Recruit.Vacancies.Jobs/Schedules.cs, src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/DeleteStaleQueryStoreDocumentsQueueTrigger.cs, src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/DeleteStaleVacanciesQueueTrigger.cs, src/Jobs/Recruit.Vacancies.Jobs/Triggers/TimerTriggers/DeleteStaleVacanciesTimeTrigger.cs, src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/DeleteVacancyCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Application/Queues/Messages/DeleteStaleVacanciesQueueMessage.cs, src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IVacancyQuery.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/ProviderRelationship/ProviderRelationshipsService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProvider/TrainingProviderService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/StorageQueue/QueueNames.cs, src/Shared/UnitTests/Vacancies.Client/Application/CommandHandlers/DeleteVacancyCommandHandlerTests.cs
Continuing to use the configuration collection to allow configuring un-essential bits for the jobs. To fall back on missing configuration a default value based on the story is applied. 
Changed the DeleteVacancyCommandHandler to make the user optional as when we delete the vacancy via the job there is no associated user.
=> ER-1519 housekeeping on vacancies

src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/BeginMigrationQueueTrigger.cs, src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/PerformDataMigrationQueueTrigger.cs, src/Shared/Recruit.Vacancies.Client/Application/Queues/Messages/DataMigrationQueueMessage.cs, src/Shared/Recruit.Vacancies.Client/Domain/Repositories/IVacancyQuery.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbVacancyRepository.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/StorageQueue/QueueNames.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/StorageQueue/RecruitStorageQueueService.cs
This is a data migration task. The code changes made here will be removed after the migration is done. Hence I have made precise changes only. 
There are two new web jobs. Begin migration will trigger on queue, this will allow us to trigger migration when we are ready. The handler to this will queue up all the vacancies so that migration can take place in parallel. 
The data migration listens to this queue and does the actual migration. 
This setup will be reused for any future migrations as well.
=> CON-1185 backfill vacancies with ALE id

src/API/Recruit.Api.UnitTests/Mappers/VacancyMapperTests.cs, src/API/Recruit.Api/Mappers/VacancyMapper.cs
Fix an issue where the duration was not correctly mapping from the value provided in the API to the value that is stored on the vacancy
=> FAI-621 - Fix issue with duration mapping in API

src/Provider/Provider.Web/Views/Dashboard/DashboardNoReview.cshtml
Commit Details:
Update banner
GIVEN the provider is on the dashboard page of the Recruit a Trainee service WHEN they look below the header
THEN they’ll see the banner with the updated content with new service close date
Story: https://skillsfundingagency.atlassian.net/browse/FAI-859
=> FAI-859 Update content and close date in banner in Recruit a Trainee

src/API/Recruit.Api.UnitTests/Controllers/LiveVacanciesControllerTests.cs, src/API/Recruit.Api.UnitTests/Queries/GetAllLiveVacanciesQueryHandlerTests.cs, src/API/Recruit.Api/Controllers/LiveVacanciesController.cs, src/API/Recruit.Api/Models/LiveVacanciesSummary.cs, src/API/Recruit.Api/Queries/GetLiveVacanciesQuery.cs, src/API/Recruit.Api/Queries/GetLiveVacanciesQueryHandler.cs, src/API/Recruit.Api/Queries/GetLiveVacanciesQueryResponse.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/IQueryStore.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/IQueryStoreReader.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/MongoQueryStore.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/QueryStore/QueryStoreClient.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/TableStore/TableStorageQueryStore.cs
Add endpoint to get all vacancies:
-  that have a closing date that is in the future, 
- and sort these results by closing date (in descending order)
- with a default of 100 results per page,
- and a maximum of 1000 results returned (even if the paging numbers would expect more)
=> FAI-971 Add get all live vacancies endpoint

src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/ApplicationReviewCommandHandler.cs
This is to cover the scenarios where a application has been migrated and will be a non v2 created but exists in v2 to be updated
=> FAI-1206 - change so that we always call the outer api

src/Jobs/Recruit.Vacancies.Jobs/Triggers/QueueTriggers/UpdateProviderInfoQueueTrigger.cs, src/Shared/Recruit.Vacancies.Client/Application/Queues/Messages/UpdateProviderInfoQueueMessage.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/StorageQueue/QueueNames.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/StorageQueue/RecruitStorageQueueService.cs
Can add a single message to the queue `update-provider-info-queue` in the format of:
```
{
"ukprns": [
10000001,
10000002
]
}
```
=> FAI-1889 - Add new queue trigger to refresh provider info

src/Jobs/Recruit.Vacancies.Jobs.UnitTests/AnalyticsSummaryProcessor/AnalyticsAggregatorTests.cs, src/Jobs/Recruit.Vacancies.Jobs/AnalyticsSummaryProcessor/AnalyticsAggregator.cs
Make sure that if we do receive a ML advert with - in the vacancy ref, we can still process it
=> FAI-2370 - Ensure ML adverts can have analytics data stored

src/Employer/Employer.Web/Orchestrators/VacancyManageOrchestrator.cs, src/Employer/Employer.Web/ViewModels/VacancyManage/ManageVacancyViewModel.cs, src/Employer/Employer.Web/ViewModels/VacancyView/VacancyApplicationsViewModel.cs, src/Employer/Employer.Web/Views/Shared/_VacancyApplicationsTablePartial.cshtml, src/Employer/Employer.Web/Views/Shared/_VacancySharedApplicationsTablePartial.cshtml, src/Employer/Employer.Web/Views/VacancyManage/ManageVacancy.cshtml, src/Provider/Provider.Web/Orchestrators/VacancyManageOrchestrator.cs, src/Provider/Provider.Web/ViewModels/VacancyManage/ManageVacancyViewModel.cs, src/Provider/Provider.Web/ViewModels/VacancyView/VacancyApplicationsViewModel.cs, src/Provider/Provider.Web/Views/Shared/_VacancyApplicationsTablePartial.cshtml, src/Provider/Provider.Web/Views/VacancyManage/ManageVacancy.cshtml, src/Shared/Recruit.Vacancies.Client/Domain/Extensions/AddressExtensions.cs, src/Shared/UnitTests/Shared.Web/Extensions/AddressExtensionsTests.cs
✨ Refactor application count handling in view models
- Updated `VacancyApplicationsViewModel` to use `TotalUnfilteredApplicationsCount`.
- Renamed `FilteredApplicationLabelText` to `FilteredApplicationsLabelText`.
- Modified Razor views to utilize new properties for application counts.
- Introduced `HasApplications` and `HasNoApplications` for better checks.
- Added null checks in `AddressExtensions` and corresponding unit tests.
=> FAI-2627 Add locations field and filter to the Shared applications page

src/Shared/Recruit.Vacancies.Client/Application/CommandHandlers/CreateApplicationReviewCommandHandler.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Repositories/MongoDbApplicationReviewRepository.cs
This method is only used to check if a user has already submitted, or if they can withdraw so having it always filter out withdrawn is ok
=> FAI-2630 - Always exclude withdrawn apps from get

src/Provider/Provider.Web/Orchestrators/VacanciesOrchestrator.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/OuterApi/Requests/GetEmployerDashboardVacanciesApiRequest.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/OuterApi/Requests/GetProviderDashboardVacanciesApiRequest.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/EmployerAccount/EmployerAccountProvider.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/EmployerAccount/IEmployerAccountProvider.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProvider/ITrainingProviderService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/TrainingProvider/TrainingProviderService.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/VacancySummariesProvider/VacancySummariesProvider.cs, src/Shared/Recruit.Vacancies.Client/Infrastructure/Services/VacancySummariesProvider/VacancySummaryAggQueryBuilder.cs, src/Shared/UnitTests/Vacancies.Client/Infrastructure/OuterApi/Requests/WhenBuildingGetEmployerVacanciesDashboardApiRequest.cs, src/Shared/UnitTests/Vacancies.Client/Infrastructure/OuterApi/Requests/WhenBuildingGetProviderVacanciesDashboardApiRequest.cs, src/Shared/UnitTests/Vacancies.Client/Infrastructure/Services/EmployerAccount/EmployerAccountProviderTests.cs, src/Shared/UnitTests/Vacancies.Client/Infrastructure/Services/TrainingProviderServiceTests.cs
Notes on Mismatched Numbers
Issue 1: Pagination Limit
The method used to fetch the count for a given status and UKPRN defaulted to a page size of 25.
This caused a discrepancy between the vacancy references retrieved from the Mongo collection and the list returned by the Recruit Inner API, since the API only returned 25 items at a time.
Fix:
The default page size has been increased to 1000 as a temporary solution, until the full migration of VacancyReviews to SQL is complete.
Issue 2: OwnerType Inconsistency
There are some vacancies (e.g., 1000010503, 1000014343) where permissions were revoked.
For these vacancies, the OwnerType is showing as Employer, even though the source is showing correctly as ProviderWeb.
In the Recruit SQL, the OwnerType is still showing as Provider.
This mismatch …
=> FAI-2733 Bug Dashboard Numbers not matching

src/QA/QA.Web/Views/Review/ReadonlyReview.cshtml, src/QA/QA.Web/Views/Review/Review.cshtml, src/QA/QA.Web/wwwroot/css/application.css
✨ Enhance application URL links and styling
- Added `das-hyperlink-wrapper` class to anchor elements.
- Ensured application URLs are displayed as clickable text.
- Introduced CSS styles for improved text wrapping and display.
- Modified `.float-right` class for better element positioning.
- Improved overall link responsiveness and visual appeal.
=> FAI-2754 Update QA review screen to ensure long URLs wrap

src/Provider/Provider.Web/Views/Part1/Training/Training.cshtml
✨ Enhance link styling in Training.cshtml
- Added `govuk-link` and `govuk-link--no-visited-state` classes.
- Improved the appearance and behavior of the standards management link.
- Ensured consistency with other links in the application.
=> FAI-2781 Incorrect link style on provider recruit select training screen
